/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.SystemAdmin;

import Model.Account.AccountDirectory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import Model.Database.DBconnection;
import Model.Enterprise.Hospital.HospitalDirectory;
import Model.People.DietitianDirectory;
import Model.People.UserDirectory;
import Model.Utilities.UtilityFunctions;
import UI.Authenticate.LoginFrame;
import UI.SystemAdmin.ManageHospitalSA;
import UI.SystemAdmin.ManageGroceryStoresSA;
import UI.SystemAdmin.ManageMealServiceSA;
import UI.SystemAdmin.SAHomePage;
import UI.SystemAdmin.ManageUsersSA;
import java.awt.Color;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author vipul
 */
public class ManageDietitiansSA extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    UserDirectory records = new UserDirectory();
    private TableRowSorter sorter;
    public ManageDietitiansSA() {
        initComponents();
        //this.records = records;
        
        populateTableData();
        
        
        generateHospitalDropDown();
        generateHospitalDropDown1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGender = new javax.swing.ButtonGroup();
        btnGroupDiabetes = new javax.swing.ButtonGroup();
        txtAllergies4 = new javax.swing.JTextField();
        pnlTitleBar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlWorkArea = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        pnlRegistration = new javax.swing.JPanel();
        panelMedical = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        comboGender = new javax.swing.JComboBox<>();
        lblBloodGroup = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblDiabetes = new javax.swing.JLabel();
        lblAllergies = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        lblHeight = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblAllergies2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblAllergies3 = new javax.swing.JLabel();
        lblAllergies4 = new javax.swing.JLabel();
        pwdRePassword = new javax.swing.JPasswordField();
        pwdPassword = new javax.swing.JPasswordField();
        dateDOB = new com.toedter.calendar.JDateChooser();
        btnRegister = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        panelDiet = new javax.swing.JPanel();
        lblPurpose = new javax.swing.JLabel();
        comboType = new javax.swing.JComboBox<>();
        comboHospital = new javax.swing.JComboBox<>();
        lblWorkoutFrequency2 = new javax.swing.JLabel();
        txtQualification = new javax.swing.JTextField();
        lblWorkoutFrequency3 = new javax.swing.JLabel();
        txtSlots = new javax.swing.JTextField();
        lblWorkoutFrequency4 = new javax.swing.JLabel();
        dateDOJ = new com.toedter.calendar.JDateChooser();
        lblWorkoutFrequency5 = new javax.swing.JLabel();
        pnlView = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableView = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        panelMedical1 = new javax.swing.JPanel();
        txtName1 = new javax.swing.JTextField();
        comboGender1 = new javax.swing.JComboBox<>();
        lblBloodGroup2 = new javax.swing.JLabel();
        lblWeight2 = new javax.swing.JLabel();
        lblDiabetes2 = new javax.swing.JLabel();
        lblAllergies5 = new javax.swing.JLabel();
        txtContact1 = new javax.swing.JTextField();
        lblHeight2 = new javax.swing.JLabel();
        txtAddress1 = new javax.swing.JTextField();
        lblAllergies6 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        lblAllergies7 = new javax.swing.JLabel();
        lblAllergies8 = new javax.swing.JLabel();
        pwdRePassword1 = new javax.swing.JPasswordField();
        pwdPassword1 = new javax.swing.JPasswordField();
        dateDOB1 = new com.toedter.calendar.JDateChooser();
        panelDiet1 = new javax.swing.JPanel();
        comboType1 = new javax.swing.JComboBox<>();
        comboHospital1 = new javax.swing.JComboBox<>();
        txtQualification1 = new javax.swing.JTextField();
        txtSlots1 = new javax.swing.JTextField();
        dateDOJ1 = new com.toedter.calendar.JDateChooser();
        lblPurpose1 = new javax.swing.JLabel();
        lblWorkoutFrequency10 = new javax.swing.JLabel();
        lblWorkoutFrequency11 = new javax.swing.JLabel();
        lblWorkoutFrequency12 = new javax.swing.JLabel();
        lblWorkoutFrequency13 = new javax.swing.JLabel();
        pnlSideOptions = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lblStore = new javax.swing.JLabel();
        lblService = new javax.swing.JLabel();

        txtAllergies4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAllergies4KeyTyped(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(66, 179, 172));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTitleBar.setBackground(new java.awt.Color(100, 129, 152));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_menu_48px_1.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel4.setText("Welcome, System Admin");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Diet Management System");

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTitleBarLayout = new javax.swing.GroupLayout(pnlTitleBar);
        pnlTitleBar.setLayout(pnlTitleBarLayout);
        pnlTitleBarLayout.setHorizontalGroup(
            pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleBarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 575, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
            .addGroup(pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleBarLayout.createSequentialGroup()
                    .addContainerGap(732, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(59, 59, 59)))
        );
        pnlTitleBarLayout.setVerticalGroup(
            pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleBarLayout.createSequentialGroup()
                .addGroup(pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTitleBarLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlTitleBarLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleBarLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addContainerGap()))
        );

        getContentPane().add(pnlTitleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 60));

        pnlWorkArea.setBackground(new java.awt.Color(255, 255, 255));
        pnlWorkArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabbedPane.setBackground(new java.awt.Color(255, 51, 51));
        tabbedPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabbedPane.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        tabbedPane.setName(""); // NOI18N

        pnlRegistration.setBackground(new java.awt.Color(255, 255, 255));

        panelMedical.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelMedical.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelMedical.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });
        panelMedical.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 200, 30));

        comboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Non-Binary", "Prefer not to say" }));
        comboGender.setSelectedIndex(-1);
        panelMedical.add(comboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, 30));

        lblBloodGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/userIcons/icons8-male-and-female-29.png"))); // NOI18N
        lblBloodGroup.setText("           Gender");
        panelMedical.add(lblBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lblWeight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons/icons8-phone-30.png"))); // NOI18N
        lblWeight.setText("            Phone");
        panelMedical.add(lblWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblDiabetes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons/icons8-birth-date-30.png"))); // NOI18N
        lblDiabetes.setText(" Date of Birth");
        panelMedical.add(lblDiabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, -1));

        lblAllergies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons/icons8-password-30.png"))); // NOI18N
        lblAllergies.setText("Confirm Password");
        panelMedical.add(lblAllergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactKeyTyped(evt);
            }
        });
        panelMedical.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, 30));

        lblHeight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/userIcons/icons8-name-tag-29.png"))); // NOI18N
        lblHeight.setText("             Name");
        panelMedical.add(lblHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, -1));

        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddressKeyTyped(evt);
            }
        });
        panelMedical.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 190, 30));

        lblAllergies2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/userIcons/icons8-home-address-29 (1).png"))); // NOI18N
        lblAllergies2.setText("                  Address");
        panelMedical.add(lblAllergies2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });
        panelMedical.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 190, 30));

        lblAllergies3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons/mail_30px.png"))); // NOI18N
        lblAllergies3.setText("                      Email");
        panelMedical.add(lblAllergies3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        lblAllergies4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons/icons8-password-30.png"))); // NOI18N
        lblAllergies4.setText("               Password");
        panelMedical.add(lblAllergies4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));
        panelMedical.add(pwdRePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 190, 30));
        panelMedical.add(pwdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 190, 30));
        panelMedical.add(dateDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 200, 30));

        btnRegister.setBackground(new java.awt.Color(255, 51, 51));
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 51, 51));
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        panelDiet.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profession Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPurpose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/hospital/icons8-hospital-29.png"))); // NOI18N
        lblPurpose.setText("        Hospital");
        panelDiet.add(lblPurpose, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consultant", "Clinical", "Pediatric", "Sports", "Research" }));
        comboType.setSelectedIndex(-1);
        comboType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTypeActionPerformed(evt);
            }
        });
        panelDiet.add(comboType, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, 30));

        panelDiet.add(comboHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 200, 30));

        lblWorkoutFrequency2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/dietitian/icons8-benficiary-29.png"))); // NOI18N
        lblWorkoutFrequency2.setText("              Type");
        panelDiet.add(lblWorkoutFrequency2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtQualification.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualificationKeyTyped(evt);
            }
        });
        panelDiet.add(txtQualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, 30));

        lblWorkoutFrequency3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/dietitian/icons8-qualification-29.png"))); // NOI18N
        lblWorkoutFrequency3.setText(" Qualification");
        panelDiet.add(lblWorkoutFrequency3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtSlots.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSlotsKeyTyped(evt);
            }
        });
        panelDiet.add(txtSlots, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 200, 30));

        lblWorkoutFrequency4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/userIcons/icons8-age-29.png"))); // NOI18N
        lblWorkoutFrequency4.setText("      Date of Joining");
        panelDiet.add(lblWorkoutFrequency4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));
        panelDiet.add(dateDOJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 200, 30));

        lblWorkoutFrequency5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/dietitian/icons8-appointment-time-29.png"))); // NOI18N
        lblWorkoutFrequency5.setText("Appointment Slots");
        panelDiet.add(lblWorkoutFrequency5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        javax.swing.GroupLayout pnlRegistrationLayout = new javax.swing.GroupLayout(pnlRegistration);
        pnlRegistration.setLayout(pnlRegistrationLayout);
        pnlRegistrationLayout.setHorizontalGroup(
            pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistrationLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistrationLayout.createSequentialGroup()
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(302, 302, 302))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistrationLayout.createSequentialGroup()
                        .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelDiet, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelMedical, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
        );
        pnlRegistrationLayout.setVerticalGroup(
            pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrationLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(panelMedical, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(panelDiet, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Registration", pnlRegistration);

        pnlView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        pnlView.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 318, 28));

        tableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Gender", "Age", "Contact", "Address", "Hospital", "Type", "Qualification", "Experience", "Slots Available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Long.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableView);

        pnlView.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 770, 90));

        btnUpdate.setBackground(new java.awt.Color(255, 51, 51));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlView.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 102, 35));

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlView.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 102, 35));

        panelMedical1.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelMedical1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelMedical1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtName1KeyTyped(evt);
            }
        });
        panelMedical1.add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 200, 30));

        comboGender1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Non-Binary", "Prefer not to say" }));
        comboGender1.setSelectedIndex(-1);
        panelMedical1.add(comboGender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, 30));

        lblBloodGroup2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/userIcons/icons8-male-and-female-29.png"))); // NOI18N
        lblBloodGroup2.setText("           Gender");
        panelMedical1.add(lblBloodGroup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lblWeight2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons/icons8-phone-30.png"))); // NOI18N
        lblWeight2.setText("            Phone");
        panelMedical1.add(lblWeight2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblDiabetes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons/icons8-birth-date-30.png"))); // NOI18N
        lblDiabetes2.setText("Date  of Birth");
        panelMedical1.add(lblDiabetes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, -1));

        lblAllergies5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons/icons8-password-30.png"))); // NOI18N
        lblAllergies5.setText("Confirm Password");
        panelMedical1.add(lblAllergies5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        txtContact1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContact1KeyTyped(evt);
            }
        });
        panelMedical1.add(txtContact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, 30));

        lblHeight2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/userIcons/icons8-name-tag-29.png"))); // NOI18N
        lblHeight2.setText("             Name");
        panelMedical1.add(lblHeight2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, -1));

        txtAddress1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddress1KeyTyped(evt);
            }
        });
        panelMedical1.add(txtAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 190, 30));

        lblAllergies6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/userIcons/icons8-home-address-29 (1).png"))); // NOI18N
        lblAllergies6.setText("                  Address");
        panelMedical1.add(lblAllergies6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        txtEmail1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmail1KeyTyped(evt);
            }
        });
        panelMedical1.add(txtEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 190, 30));

        lblAllergies7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons/mail_30px.png"))); // NOI18N
        lblAllergies7.setText("                      Email");
        panelMedical1.add(lblAllergies7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        lblAllergies8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons/icons8-password-30.png"))); // NOI18N
        lblAllergies8.setText("               Password");
        panelMedical1.add(lblAllergies8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));
        panelMedical1.add(pwdRePassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 190, 30));
        panelMedical1.add(pwdPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 190, 30));
        panelMedical1.add(dateDOB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 200, 30));

        pnlView.add(panelMedical1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 770, 200));

        panelDiet1.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profession Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consultant", "Clinical", "Pediatric", "Sports", "Research" }));
        comboType1.setSelectedIndex(-1);
        comboType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboType1ActionPerformed(evt);
            }
        });
        panelDiet1.add(comboType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        comboHospital1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Independent", "Boston General", "Noble Care" }));
        comboHospital1.setSelectedIndex(-1);
        panelDiet1.add(comboHospital1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 200, 30));

        txtQualification1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification1KeyTyped(evt);
            }
        });
        panelDiet1.add(txtQualification1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, 30));

        txtSlots1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSlots1KeyTyped(evt);
            }
        });
        panelDiet1.add(txtSlots1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 200, 30));
        panelDiet1.add(dateDOJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 200, 30));

        lblPurpose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/hospital/icons8-hospital-29.png"))); // NOI18N
        lblPurpose1.setText("        Hospital");
        panelDiet1.add(lblPurpose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblWorkoutFrequency10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/dietitian/icons8-benficiary-29.png"))); // NOI18N
        lblWorkoutFrequency10.setText("              Type");
        panelDiet1.add(lblWorkoutFrequency10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lblWorkoutFrequency11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/dietitian/icons8-qualification-29.png"))); // NOI18N
        lblWorkoutFrequency11.setText(" Qualification");
        panelDiet1.add(lblWorkoutFrequency11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lblWorkoutFrequency12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/userIcons/icons8-age-29.png"))); // NOI18N
        lblWorkoutFrequency12.setText("      Date of Joining");
        panelDiet1.add(lblWorkoutFrequency12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        lblWorkoutFrequency13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/dietitian/icons8-appointment-time-29.png"))); // NOI18N
        lblWorkoutFrequency13.setText("Appointment Slots");
        panelDiet1.add(lblWorkoutFrequency13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        pnlView.add(panelDiet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 770, 150));

        tabbedPane.addTab("Modifications", pnlView);

        pnlWorkArea.add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -9, 820, 620));

        getContentPane().add(pnlWorkArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 63, 810, 610));

        pnlSideOptions.setBackground(new java.awt.Color(51, 51, 51));
        pnlSideOptions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(192, 202, 97));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        jLabel1.setText("   Logout");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, -1));

        pnlSideOptions.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 190, 45));

        jPanel7.setBackground(new java.awt.Color(255, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel8.setText("  Home Page");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 45));

        jPanel9.setBackground(new java.awt.Color(255, 51, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel9.setText("  Home Page");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel10.setBackground(new java.awt.Color(255, 51, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel10.setText("  Home Page");
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 45));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 45));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/Icon-Small.png"))); // NOI18N
        jLabel13.setText(" Manage Dietitians");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pnlSideOptions.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, 45));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/Icon-Small_1.png"))); // NOI18N
        jLabel14.setText(" Manage Hospitals");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        pnlSideOptions.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 170, -1));

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel11.setText("  Home Page");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, -1));

        pnlSideOptions.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 45));

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/users_sadmin_29px.png"))); // NOI18N
        jLabel18.setText(" Manage Users");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, -1));

        pnlSideOptions.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 190, 45));

        lblStore.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        lblStore.setForeground(new java.awt.Color(255, 255, 255));
        lblStore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/product_sadmin_29px.png"))); // NOI18N
        lblStore.setText(" Manage Stores");
        lblStore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStoreMouseClicked(evt);
            }
        });
        pnlSideOptions.add(lblStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 180, -1));

        lblService.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        lblService.setForeground(new java.awt.Color(255, 255, 255));
        lblService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/product_sadmin_29px.png"))); // NOI18N
        lblService.setText(" Manage Services");
        lblService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblServiceMouseClicked(evt);
            }
        });
        pnlSideOptions.add(lblService, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 180, -1));

        getContentPane().add(pnlSideOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 190, 620));

        setSize(new java.awt.Dimension(1014, 673));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void generateHospitalDropDown() {
        
        HospitalDirectory hd = new HospitalDirectory();
        List<String> hospitalList = hd.getAllHospitalsList();
        
        String[] foodDropdown = hospitalList.toArray(new String[hospitalList.size()]);
        DefaultComboBoxModel<String> yearsSDropdownModel = new DefaultComboBoxModel<>(foodDropdown);
        comboHospital.setModel(yearsSDropdownModel);
        comboHospital.setSelectedIndex(-1);
        
    }
    
    public void generateHospitalDropDown1() {
        
        HospitalDirectory hd = new HospitalDirectory();
        List<String> hospitalList = hd.getAllHospitalsList();
        
        String[] foodDropdown = hospitalList.toArray(new String[hospitalList.size()]);
        DefaultComboBoxModel<String> yearsSDropdownModel = new DefaultComboBoxModel<>(foodDropdown);
        comboHospital1.setModel(yearsSDropdownModel);
        comboHospital1.setSelectedIndex(-1);
        
    }
    
    public void resetUpdateForm(){
      
        txtName1.setText(null);
        dateDOB1.setDate(null);
        comboGender1.setSelectedIndex(-1);
        txtContact1.setText(null);
        txtAddress1.setText(null);
        comboHospital1.setSelectedIndex(-1);
        txtQualification1.setText(null);
        
        txtEmail1.setText(null);
        pwdPassword1.setText(null);
        pwdRePassword1.setText(null);
        
        dateDOJ1.setDate(null);
        comboType1.setSelectedIndex(-1);
        txtSlots1.setText(null);
         
    }

    public void resetForm(){
        
        txtName.setText(null);
        dateDOB.setDate(null);
        comboGender.setSelectedIndex(-1);
        txtContact.setText(null);
        txtAddress.setText(null);
        comboHospital.setSelectedIndex(-1);
        txtQualification.setText(null);
        
        txtEmail.setText(null);
        pwdPassword.setText(null);
        pwdRePassword.setText(null);
        dateDOJ.setDate(null);
        comboType.setSelectedIndex(-1);
        txtSlots.setText(null);
         
    }
    
    
    public LocalDate convertToLocalDateViaInstant(Date dateToConvert) {
        return dateToConvert.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }
    
    
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        
        if(true){
            //Personal Info
            String name = txtName.getText();
            Date dob = dateDOB.getDate();
            LocalDate today = LocalDate.now();
            int age = Period.between(convertToLocalDateViaInstant(dob), today).getYears();
            System.out.print(age);
            String gender = comboGender.getSelectedItem().toString();
            long contact = Long.parseLong(txtContact.getText());
            //add line for photo (ImageIcon)

           //Address
           String address = txtAddress.getText();
           
           //Health details
           String hospital = comboHospital.getSelectedItem().toString();
           String qualification = txtQualification.getText();
           
           Date doj = dateDOJ.getDate();
           int experience = Period.between(convertToLocalDateViaInstant(doj), today).getYears();
           String type = comboType.getSelectedItem().toString();
           int slots = Integer.parseInt(txtSlots.getText());
           
           String email = txtEmail.getText();
           String password =new String(pwdPassword.getPassword());
           String confirmpassword = new String(pwdRePassword.getPassword());
           
           new DietitianDirectory().addNewDietitianToDB(name, dob, age, gender, contact, address, doj, experience, qualification, slots, hospital, type, email);
           
        if (email.equals("Enter Email") || password.equals("Enter Password") 
                || confirmpassword.equals("Confirm Password") ){
            JOptionPane.showMessageDialog(this, "Please fill all the fields!");
        }
        else if (!password.equals(confirmpassword)){
            System.out.println(password);
            System.out.println(confirmpassword);
            JOptionPane.showMessageDialog(this, "Password doesn't match!");
        }
        else{
            AccountDirectory ac = new AccountDirectory();
            if (comboType.getSelectedItem().toString().equals("Research")){
                ac.addUserCredential(email, password, "Research Dietitian");
            }
            else{
                ac.addUserCredential(email, password, "Dietitian");
                
                JOptionPane.showMessageDialog(this, "Account Created Successfully");

                resetForm();
            }
            
        }
           
           
           populateTableData();
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        // TODO add your handling code here:
        char typedName = evt.getKeyChar();
        if(!Character.isAlphabetic(typedName) && !Character.isWhitespace(typedName)){
            evt.consume();
        }
        //Restrict the length to 256 
        if(txtName.getText().length() > 255){
                evt.consume();
        }
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyTyped
        // TODO add your handling code here:
        char typedPhoneNumber = evt.getKeyChar();
        if(!Character.isDigit(typedPhoneNumber)){
            evt.consume();
        }
        //Restrict the length to 10 
        if(txtContact.getText().length() > 9){
                evt.consume();
        }
    }//GEN-LAST:event_txtContactKeyTyped

    private void comboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTypeActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int rowIndex = tableView.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tableView.getModel();
//        User selectedUser =(User)model.getValueAt(rowIndex,1);
        
        int id = Integer.parseInt(model.getValueAt(rowIndex,0).toString());
        
        String name = txtName1.getText();
        Date dob = dateDOB1.getDate();
        String gender = comboGender1.getSelectedItem().toString();
        Long contact = Long.parseLong(txtContact1.getText());
        String address = txtAddress1.getText();
        Date doj = dateDOJ1.getDate();
        String qualification = txtQualification1.getText();
        String hospital = comboHospital1.getSelectedItem().toString();
        String type = comboType1.getSelectedItem().toString();
        int slots = Integer.parseInt(txtSlots1.getText());
        
        DietitianDirectory dd = new DietitianDirectory();
        dd.updateRecordsByID(name, dob, gender, contact, address, doj, qualification, hospital, type, slots, id);
        JOptionPane.showMessageDialog(this, "Account Updated Successfully");
        populateTableData();
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        LoginFrame frame = new LoginFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        SAHomePage frame = new SAHomePage();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        int rowIndex = tableView.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tableView.getModel();
        
        int id = Integer.parseInt(model.getValueAt(rowIndex,0).toString());
        
        DietitianDirectory dd = new DietitianDirectory();
        dd.deleteDietitianFromDB(id);
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tableViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableViewMouseClicked
        // TODO add your handling code here:
        int rowIndex = tableView.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tableView.getModel();
        
        int id = Integer.parseInt(model.getValueAt(rowIndex,0).toString());
        
        DietitianDirectory dd = new DietitianDirectory();
        ResultSet res = dd.selectRecordsByID(id);
        
        try{
            
            while(res.next()){
                
                txtName1.setText(res.getString("Name"));
                dateDOB1.setDate(res.getDate("DOB"));
                comboGender1.setSelectedItem(res.getString("Gender"));
                txtContact1.setText(String.valueOf(res.getLong("Contact")));
                txtAddress1.setText(res.getString("Address"));
                
                txtEmail1.setText(res.getString("Email"));
                comboHospital1.setSelectedItem(res.getString("Hospital"));
                txtQualification1.setText(res.getString("Qualification"));
                dateDOJ1.setDate(res.getDate("DOJ"));
                comboType1.setSelectedItem(res.getString("Type"));
                txtSlots1.setText(String.valueOf(res.getInt("Slots")));
                
            }
            
        }
        catch(SQLException ex){
            Logger.getLogger(ManageDietitiansSA.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_tableViewMouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setForeground(Color.red);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel3.setForeground(Color.white);
    }//GEN-LAST:event_jLabel3MouseExited

    private void txtAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtAllergies4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAllergies4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAllergies4KeyTyped

    private void txtQualificationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualificationKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualificationKeyTyped

    private void txtSlotsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSlotsKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSlotsKeyTyped

    private void txtName1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtName1KeyTyped
        // TODO add your handling code here:
        char typedName = evt.getKeyChar();
        if(!Character.isAlphabetic(typedName) && !Character.isWhitespace(typedName)){
            evt.consume();
        }
        //Restrict the length to 256 
        if(txtName1.getText().length() > 255){
                evt.consume();
        }
    }//GEN-LAST:event_txtName1KeyTyped

    private void txtContact1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContact1KeyTyped
        // TODO add your handling code here:
        char typedPhoneNumber = evt.getKeyChar();
        if(!Character.isDigit(typedPhoneNumber)){
            evt.consume();
        }
        //Restrict the length to 10 
        if(txtContact1.getText().length() > 9){
                evt.consume();
        }
    }//GEN-LAST:event_txtContact1KeyTyped

    private void txtAddress1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddress1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddress1KeyTyped

    private void txtEmail1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmail1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail1KeyTyped

    private void comboType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboType1ActionPerformed

    private void txtQualification1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification1KeyTyped

    private void txtSlots1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSlots1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSlots1KeyTyped

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        ManageUsersSA frame = new ManageUsersSA();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        ManageHospitalSA frame = new ManageHospitalSA();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void lblStoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStoreMouseClicked
        // TODO add your handling code here:
        ManageGroceryStoresSA frame = new ManageGroceryStoresSA();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblStoreMouseClicked

    private void lblServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblServiceMouseClicked
        // TODO add your handling code here:
        ManageMealServiceSA frame = new ManageMealServiceSA();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblServiceMouseClicked
    
    boolean isDataValid(){
//        String id, name, emailId, gender, community, city, state, username ;
//        String houseNumber, zipCode, age, bloodGroup, height, weight;
//        String contactDetails;
////        Date dob;
//        //String patternEmail = "^[A-Za-z0-9+_.-]+@(.+)$";
//        String patternEmail = "^[(a-zA-Z-0-9-\\_\\+\\.)]+@[(a-z-A-z)]+\\.[(a-zA-z)]{2,3}$";
//        String bmi = "[(0-9\\.)]{2,}$";
//               
//        id = txtDoctorID.getText();
//        name = txtName.getText();
//        emailId = txtEmail.getText();
//        contactDetails = txtContact.getText();
//        age = txtAge.getText();
////        dob = DOBtxt.getDate();
//        if(comboPurpose.getSelectedItem() == null){
//            houseNumber = "";
//        }
//        else{
//            houseNumber = comboPurpose.getSelectedItem().toString();
//        }
//        
//        
//        if(comboCommunity.getSelectedItem() == null){
//            community = "";
//        }
//        else{
//            community = comboCommunity.getSelectedItem().toString();
//        }
//        
//        
//        if(comboCity.getSelectedItem() == null){
//            city = "";
//        }
//        else{
//            city = comboCity.getSelectedItem().toString();
//        }
//        state = txtState.getText();
//        zipCode = txtZipCode.getText();
//        //bloodGroup = (String) patientBloodGroupTxt.getSelectedItem();
//        String qualification = txtQualification.getText();
//        String specialization = txtSpecialization.getText();
//        String slots = txtHeight.getText();
//        String password = new String(txtPassword.getText());
//        String rePassword = new String(txtPassword2.getPassword());
//        
//        
//       
//        if(comboGender.getSelectedItem() == null){
//            gender = "";
//        }
//        else{
//            gender = comboGender.getSelectedItem().toString(); 
//        }
//        
//        String hospital;
//        if(comboBloodGroup.getSelectedItem() == null){
//            hospital = "";
//        }
//        else{
//            hospital = comboBloodGroup.getSelectedItem().toString(); 
//        }
//        
//        
//        if (id.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter Patient ID");
//            return false;
//        }
//       
//        if (name.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter name");
//            return false;
//        }
//        
//        if (gender.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please select gender");
//            return false;
//        }
//        
//        if (hospital.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please select hospital");
//            return false;
//        }
//        
//        if (contactDetails.equals("") || !(txtContact.getText().length()==10))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter valid contact Number");
//            txtContact.setText("");
//           
//            return false;
//        }
//        //emailIDTxt.getText().isBlank() &&
//        if( !txtEmail.getText().matches(patternEmail)){
//                JOptionPane.showMessageDialog(this, "Please enter a valid Email.");
//                txtEmail.setText("");
//                return false;
//            }
//       
//        if (age.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter age");
//            return false;
//        }
//       
//        if (slots.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter number of slots available");
//            return false;
//        }
//        
//        if (qualification.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter qualification");
//            return false;
//        }
//        if (specialization.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter specialization");
//            return false;
//        }
       
       
//        if (zipCode.equals("") || !(txtZipCode.getText().length()==5))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter zipCode");
//            txtZipCode.setText("");
//            return false;
//        }
//       
//   
//       
//        if (password.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter password");
//            return false;
//        }
//       
//        if (rePassword.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter rePassword");
//            return false;
//        }
//       
//        if (!(password).equals(rePassword)){
//            JOptionPane.showMessageDialog(this, "Password doesn't match");
//            return false;
//        }
       
        return true;
       
    }
    
    private void populateTableData() {
        
        //Type-cast table model into default table model
        DefaultTableModel model = (DefaultTableModel) tableView.getModel();
        
        sorter = new TableRowSorter<>(model);

        tableView.setRowSorter(sorter);
        //Clear the table 
        model.setRowCount(0);
        
        DietitianDirectory dd = new DietitianDirectory();
        ResultSet res = dd.selectAllRecords();
        try{
            
            while(res.next()){
                Object[] row = new Object[11];
                row[0] = res.getInt("ID");
                row[1] = res.getString("Name");
                row[2] = res.getString("Gender");
                row[3] = res.getInt("Age");
                row[4] = res.getLong("Contact");
                row[5] = res.getString("Address");
                row[6] = res.getString("Hospital");
                row[7] = res.getString("Type");
                row[8] = res.getString("Qualification");
                row[9] = res.getInt("Experience");
                row[10] = res.getInt("Slots");
                
                model.addRow(row);
            }
            System.out.println(res);
            
//            tableView.setModel(DbUtils.resultSetToTableModel(res));
        }
        catch(SQLException ex){
            Logger.getLogger(ManageDietitiansSA.class.getName()).log(Level.SEVERE, null, ex);
        }
      
      //--------------
        txtSearch.getDocument().addDocumentListener(new DocumentListener() {
         @Override
         public void insertUpdate(DocumentEvent e) {
            search(txtSearch.getText());
         }
         @Override
         public void removeUpdate(DocumentEvent e) {
            search(txtSearch.getText());
         }
         @Override
         public void changedUpdate(DocumentEvent e) {
            search(txtSearch.getText());
         }
         public void search(String str) {
            if (str.length() == 0) {
               sorter.setRowFilter(null);
            } else {
               sorter.setRowFilter(RowFilter.regexFilter(str));
            }
         }
      });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageDietitiansSA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.ButtonGroup btnGroupDiabetes;
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboGender;
    private javax.swing.JComboBox<String> comboGender1;
    private javax.swing.JComboBox<String> comboHospital;
    private javax.swing.JComboBox<String> comboHospital1;
    private javax.swing.JComboBox<String> comboType;
    private javax.swing.JComboBox<String> comboType1;
    private com.toedter.calendar.JDateChooser dateDOB;
    private com.toedter.calendar.JDateChooser dateDOB1;
    private com.toedter.calendar.JDateChooser dateDOJ;
    private com.toedter.calendar.JDateChooser dateDOJ1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAllergies;
    private javax.swing.JLabel lblAllergies2;
    private javax.swing.JLabel lblAllergies3;
    private javax.swing.JLabel lblAllergies4;
    private javax.swing.JLabel lblAllergies5;
    private javax.swing.JLabel lblAllergies6;
    private javax.swing.JLabel lblAllergies7;
    private javax.swing.JLabel lblAllergies8;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblBloodGroup2;
    private javax.swing.JLabel lblDiabetes;
    private javax.swing.JLabel lblDiabetes2;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblHeight2;
    private javax.swing.JLabel lblPurpose;
    private javax.swing.JLabel lblPurpose1;
    private javax.swing.JLabel lblService;
    private javax.swing.JLabel lblStore;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblWeight2;
    private javax.swing.JLabel lblWorkoutFrequency10;
    private javax.swing.JLabel lblWorkoutFrequency11;
    private javax.swing.JLabel lblWorkoutFrequency12;
    private javax.swing.JLabel lblWorkoutFrequency13;
    private javax.swing.JLabel lblWorkoutFrequency2;
    private javax.swing.JLabel lblWorkoutFrequency3;
    private javax.swing.JLabel lblWorkoutFrequency4;
    private javax.swing.JLabel lblWorkoutFrequency5;
    private javax.swing.JPanel panelDiet;
    private javax.swing.JPanel panelDiet1;
    private javax.swing.JPanel panelMedical;
    private javax.swing.JPanel panelMedical1;
    private javax.swing.JPanel pnlRegistration;
    private javax.swing.JPanel pnlSideOptions;
    private javax.swing.JPanel pnlTitleBar;
    private javax.swing.JPanel pnlView;
    private javax.swing.JPanel pnlWorkArea;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JPasswordField pwdPassword1;
    private javax.swing.JPasswordField pwdRePassword;
    private javax.swing.JPasswordField pwdRePassword1;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tableView;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAllergies4;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtContact1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtQualification;
    private javax.swing.JTextField txtQualification1;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSlots;
    private javax.swing.JTextField txtSlots1;
    // End of variables declaration//GEN-END:variables
}
