/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.NutritionAdmin;

import UI.Main.*;
import UI.User.*;
import Model.People.User;
import Model.People.UserDirectory;
import Model.Organization.ProductDirectory;
import Model.WorkRequest.ProductApproval;

import Model.Organization.ProductDirectory;
import UI.Authenticate.LoginFrame;
import UI.SystemAdmin.SAHomePage;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author vipul
 */
public class ManageProductsNA extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form NewJFrame
     */
    UserDirectory records = new UserDirectory();
    private TableRowSorter sorter;
    public ManageProductsNA() {
        initComponents();
        populateTable();
        //this.records = records;
        
//        populateTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGender = new javax.swing.ButtonGroup();
        btnGroupDiabetes = new javax.swing.ButtonGroup();
        pnlTitleBar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlSideOptions = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnlWorkArea = new javax.swing.JPanel();
        panelDiet1 = new javax.swing.JPanel();
        lblPurpose2 = new javax.swing.JLabel();
        lblWorkoutFrequency6 = new javax.swing.JLabel();
        txtRefQty = new javax.swing.JTextField();
        lblWorkoutFrequency7 = new javax.swing.JLabel();
        txtCarbs = new javax.swing.JTextField();
        txtCalorie = new javax.swing.JTextField();
        panelDiet2 = new javax.swing.JPanel();
        lblPurpose3 = new javax.swing.JLabel();
        lblWorkoutFrequency8 = new javax.swing.JLabel();
        txtQualification4 = new javax.swing.JTextField();
        lblWorkoutFrequency9 = new javax.swing.JLabel();
        txtQualification5 = new javax.swing.JTextField();
        txtQualification6 = new javax.swing.JTextField();
        panelDiet3 = new javax.swing.JPanel();
        lblPurpose4 = new javax.swing.JLabel();
        lblWorkoutFrequency10 = new javax.swing.JLabel();
        txtQualification7 = new javax.swing.JTextField();
        lblWorkoutFrequency11 = new javax.swing.JLabel();
        txtQualification8 = new javax.swing.JTextField();
        txtQualification9 = new javax.swing.JTextField();
        panelDiet4 = new javax.swing.JPanel();
        lblPurpose5 = new javax.swing.JLabel();
        lblWorkoutFrequency12 = new javax.swing.JLabel();
        txtQualification10 = new javax.swing.JTextField();
        lblWorkoutFrequency13 = new javax.swing.JLabel();
        txtQualification11 = new javax.swing.JTextField();
        txtQualification12 = new javax.swing.JTextField();
        txtFat = new javax.swing.JTextField();
        lblWorkoutFrequency22 = new javax.swing.JLabel();
        txtChol = new javax.swing.JTextField();
        lblWorkoutFrequency23 = new javax.swing.JLabel();
        lblWorkoutFrequency24 = new javax.swing.JLabel();
        txtProtein = new javax.swing.JTextField();
        lblWorkoutFrequency25 = new javax.swing.JLabel();
        txtSodium = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        panelDiet5 = new javax.swing.JPanel();
        lblPurpose6 = new javax.swing.JLabel();
        lblWorkoutFrequency14 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblWorkoutFrequency15 = new javax.swing.JLabel();
        txtAdd = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        panelDiet6 = new javax.swing.JPanel();
        lblPurpose7 = new javax.swing.JLabel();
        lblWorkoutFrequency16 = new javax.swing.JLabel();
        txtQualification16 = new javax.swing.JTextField();
        lblWorkoutFrequency17 = new javax.swing.JLabel();
        txtQualification17 = new javax.swing.JTextField();
        txtQualification18 = new javax.swing.JTextField();
        panelDiet7 = new javax.swing.JPanel();
        lblPurpose8 = new javax.swing.JLabel();
        lblWorkoutFrequency18 = new javax.swing.JLabel();
        txtQualification19 = new javax.swing.JTextField();
        lblWorkoutFrequency19 = new javax.swing.JLabel();
        txtQualification20 = new javax.swing.JTextField();
        txtQualification21 = new javax.swing.JTextField();
        panelDiet8 = new javax.swing.JPanel();
        lblPurpose9 = new javax.swing.JLabel();
        lblWorkoutFrequency20 = new javax.swing.JLabel();
        txtQualification22 = new javax.swing.JTextField();
        lblWorkoutFrequency21 = new javax.swing.JLabel();
        txtQualification23 = new javax.swing.JTextField();
        txtQualification24 = new javax.swing.JTextField();
        btnApprove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(66, 179, 172));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTitleBar.setBackground(new java.awt.Color(100, 129, 152));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel4.setText("Welcome, Nutrition Admin");
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Diet Management System");
        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("X");
        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTitleBarLayout = new javax.swing.GroupLayout(pnlTitleBar);
        pnlTitleBar.setLayout(pnlTitleBarLayout);
        pnlTitleBarLayout.setHorizontalGroup(
            pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleBarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 575, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
            .addGroup(pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleBarLayout.createSequentialGroup()
                    .addContainerGap(722, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(59, 59, 59)))
        );
        pnlTitleBarLayout.setVerticalGroup(
            pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleBarLayout.createSequentialGroup()
                .addGroup(pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTitleBarLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlTitleBarLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleBarLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addContainerGap()))
        );

        getContentPane().add(pnlTitleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 60));

        pnlSideOptions.setBackground(new java.awt.Color(51, 51, 51));
        pnlSideOptions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(192, 202, 97));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        jLabel1.setText("   Logout");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, -1));

        pnlSideOptions.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 190, 45));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/product_sadmin_29px.png"))); // NOI18N
        jLabel7.setText(" Manage Products");
        pnlSideOptions.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 170, -1));

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel11.setText("  Home Page");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, -1));

        pnlSideOptions.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 45));

        jPanel7.setBackground(new java.awt.Color(255, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel8.setText("  Home Page");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 45));

        jPanel9.setBackground(new java.awt.Color(255, 51, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel9.setText("  Home Page");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel10.setBackground(new java.awt.Color(255, 51, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel10.setText("  Home Page");
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 45));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 45));

        pnlSideOptions.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 45));

        getContentPane().add(pnlSideOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 190, 620));

        pnlWorkArea.setBackground(new java.awt.Color(255, 255, 255));
        pnlWorkArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDiet1.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nutritional Facts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPurpose2.setText("Reference Quantity");
        panelDiet1.add(lblPurpose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        lblWorkoutFrequency6.setText("Calorie");
        panelDiet1.add(lblWorkoutFrequency6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        txtRefQty.setEditable(false);
        txtRefQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRefQtyKeyTyped(evt);
            }
        });
        panelDiet1.add(txtRefQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 200, 30));

        lblWorkoutFrequency7.setText("Carbohydrates");
        panelDiet1.add(lblWorkoutFrequency7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        txtCarbs.setEditable(false);
        txtCarbs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCarbsKeyTyped(evt);
            }
        });
        panelDiet1.add(txtCarbs, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 200, 30));

        txtCalorie.setEditable(false);
        txtCalorie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCalorieKeyTyped(evt);
            }
        });
        panelDiet1.add(txtCalorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        panelDiet2.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nutritional Facts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPurpose3.setText("Product Name");
        panelDiet2.add(lblPurpose3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblWorkoutFrequency8.setText("Type");
        panelDiet2.add(lblWorkoutFrequency8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txtQualification4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification4KeyTyped(evt);
            }
        });
        panelDiet2.add(txtQualification4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 200, 30));

        lblWorkoutFrequency9.setText("Added By");
        panelDiet2.add(lblWorkoutFrequency9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        txtQualification5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification5KeyTyped(evt);
            }
        });
        panelDiet2.add(txtQualification5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 200, 70));

        txtQualification6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification6KeyTyped(evt);
            }
        });
        panelDiet2.add(txtQualification6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        panelDiet1.add(panelDiet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 770, 150));

        panelDiet3.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nutritional Facts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPurpose4.setText("Product Name");
        panelDiet3.add(lblPurpose4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblWorkoutFrequency10.setText("Type");
        panelDiet3.add(lblWorkoutFrequency10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txtQualification7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification7KeyTyped(evt);
            }
        });
        panelDiet3.add(txtQualification7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 200, 30));

        lblWorkoutFrequency11.setText("Added By");
        panelDiet3.add(lblWorkoutFrequency11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        txtQualification8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification8KeyTyped(evt);
            }
        });
        panelDiet3.add(txtQualification8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 200, 70));

        txtQualification9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification9KeyTyped(evt);
            }
        });
        panelDiet3.add(txtQualification9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        panelDiet4.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nutritional Facts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPurpose5.setText("Product Name");
        panelDiet4.add(lblPurpose5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblWorkoutFrequency12.setText("Type");
        panelDiet4.add(lblWorkoutFrequency12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txtQualification10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification10KeyTyped(evt);
            }
        });
        panelDiet4.add(txtQualification10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 200, 30));

        lblWorkoutFrequency13.setText("Added By");
        panelDiet4.add(lblWorkoutFrequency13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        txtQualification11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification11KeyTyped(evt);
            }
        });
        panelDiet4.add(txtQualification11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 200, 70));

        txtQualification12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification12KeyTyped(evt);
            }
        });
        panelDiet4.add(txtQualification12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        panelDiet3.add(panelDiet4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 770, 150));

        panelDiet1.add(panelDiet3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 770, 150));

        txtFat.setEditable(false);
        txtFat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFatKeyTyped(evt);
            }
        });
        panelDiet1.add(txtFat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, 30));

        lblWorkoutFrequency22.setText("Total Fat");
        panelDiet1.add(lblWorkoutFrequency22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        txtChol.setEditable(false);
        txtChol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCholKeyTyped(evt);
            }
        });
        panelDiet1.add(txtChol, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, 30));

        lblWorkoutFrequency23.setText("Cholesterol");
        panelDiet1.add(lblWorkoutFrequency23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        lblWorkoutFrequency24.setText("Protein");
        panelDiet1.add(lblWorkoutFrequency24, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        txtProtein.setEditable(false);
        txtProtein.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProteinKeyTyped(evt);
            }
        });
        panelDiet1.add(txtProtein, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 200, 30));

        lblWorkoutFrequency25.setText("Sodium");
        panelDiet1.add(lblWorkoutFrequency25, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        txtSodium.setEditable(false);
        txtSodium.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSodiumKeyTyped(evt);
            }
        });
        panelDiet1.add(txtSodium, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 200, 30));

        pnlWorkArea.add(panelDiet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 770, 180));

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        pnlWorkArea.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 770, 200));

        panelDiet5.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Facts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPurpose6.setText("Product Name");
        panelDiet5.add(lblPurpose6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblWorkoutFrequency14.setText("Type");
        panelDiet5.add(lblWorkoutFrequency14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txtName.setEditable(false);
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });
        panelDiet5.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 200, 30));

        lblWorkoutFrequency15.setText("Added By");
        panelDiet5.add(lblWorkoutFrequency15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        txtAdd.setEditable(false);
        txtAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddKeyTyped(evt);
            }
        });
        panelDiet5.add(txtAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 200, 70));

        txtType.setEditable(false);
        txtType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTypeKeyTyped(evt);
            }
        });
        panelDiet5.add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        panelDiet6.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nutritional Facts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPurpose7.setText("Product Name");
        panelDiet6.add(lblPurpose7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblWorkoutFrequency16.setText("Type");
        panelDiet6.add(lblWorkoutFrequency16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txtQualification16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification16KeyTyped(evt);
            }
        });
        panelDiet6.add(txtQualification16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 200, 30));

        lblWorkoutFrequency17.setText("Added By");
        panelDiet6.add(lblWorkoutFrequency17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        txtQualification17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification17KeyTyped(evt);
            }
        });
        panelDiet6.add(txtQualification17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 200, 70));

        txtQualification18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification18KeyTyped(evt);
            }
        });
        panelDiet6.add(txtQualification18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        panelDiet5.add(panelDiet6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 770, 150));

        panelDiet7.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nutritional Facts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPurpose8.setText("Product Name");
        panelDiet7.add(lblPurpose8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblWorkoutFrequency18.setText("Type");
        panelDiet7.add(lblWorkoutFrequency18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txtQualification19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification19KeyTyped(evt);
            }
        });
        panelDiet7.add(txtQualification19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 200, 30));

        lblWorkoutFrequency19.setText("Added By");
        panelDiet7.add(lblWorkoutFrequency19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        txtQualification20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification20KeyTyped(evt);
            }
        });
        panelDiet7.add(txtQualification20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 200, 70));

        txtQualification21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification21KeyTyped(evt);
            }
        });
        panelDiet7.add(txtQualification21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        panelDiet8.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nutritional Facts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPurpose9.setText("Product Name");
        panelDiet8.add(lblPurpose9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblWorkoutFrequency20.setText("Type");
        panelDiet8.add(lblWorkoutFrequency20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txtQualification22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification22KeyTyped(evt);
            }
        });
        panelDiet8.add(txtQualification22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 200, 30));

        lblWorkoutFrequency21.setText("Added By");
        panelDiet8.add(lblWorkoutFrequency21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        txtQualification23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification23KeyTyped(evt);
            }
        });
        panelDiet8.add(txtQualification23, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 200, 70));

        txtQualification24.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification24KeyTyped(evt);
            }
        });
        panelDiet8.add(txtQualification24, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        panelDiet7.add(panelDiet8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 770, 150));

        panelDiet5.add(panelDiet7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 770, 150));

        pnlWorkArea.add(panelDiet5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 770, 100));

        btnApprove.setBackground(new java.awt.Color(255, 51, 51));
        btnApprove.setForeground(new java.awt.Color(255, 255, 255));
        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        pnlWorkArea.add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 102, 35));

        getContentPane().add(pnlWorkArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 63, 810, 610));

        setSize(new java.awt.Dimension(1014, 673));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    
    
    public LocalDate convertToLocalDateViaInstant(Date dateToConvert) {
        return dateToConvert.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }
    
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        LoginFrame frame = new LoginFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setForeground(Color.red);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel3.setForeground(Color.white);
    }//GEN-LAST:event_jLabel3MouseExited

    private void txtCalorieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalorieKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalorieKeyTyped

    private void txtCarbsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarbsKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarbsKeyTyped

    private void txtRefQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRefQtyKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRefQtyKeyTyped

    private void txtQualification4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification4KeyTyped

    private void txtQualification5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification5KeyTyped

    private void txtQualification6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification6KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification6KeyTyped

    private void txtQualification7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification7KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification7KeyTyped

    private void txtQualification8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification8KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification8KeyTyped

    private void txtQualification9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification9KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification9KeyTyped

    private void txtQualification10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification10KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification10KeyTyped

    private void txtQualification11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification11KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification11KeyTyped

    private void txtQualification12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification12KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification12KeyTyped

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtAddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddKeyTyped

    private void txtTypeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTypeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeKeyTyped

    private void txtQualification16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification16KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification16KeyTyped

    private void txtQualification17KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification17KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification17KeyTyped

    private void txtQualification18KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification18KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification18KeyTyped

    private void txtQualification19KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification19KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification19KeyTyped

    private void txtQualification20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification20KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification20KeyTyped

    private void txtQualification21KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification21KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification21KeyTyped

    private void txtQualification22KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification22KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification22KeyTyped

    private void txtQualification23KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification23KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification23KeyTyped

    private void txtQualification24KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification24KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification24KeyTyped

    private void txtFatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFatKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFatKeyTyped

    private void txtCholKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCholKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCholKeyTyped

    private void txtProteinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProteinKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProteinKeyTyped

    private void txtSodiumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSodiumKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSodiumKeyTyped

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        try {
            // TODO add your handling code here:
            int row = tblProduct.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
            
            String product_name = model.getValueAt(row,0).toString();
            
            ProductDirectory product = new ProductDirectory();
            
            ResultSet res = product.exactProductLookup(product_name);
            while(res.next()){
                txtName.setText(res.getString(1));
                txtType.setText(res.getString(2));
                txtAdd.setText(res.getString(10));
                txtRefQty.setText(res.getString(3));
                txtCalorie.setText(res.getString(4));
                txtFat.setText(res.getString(5));
                txtChol.setText(res.getString(6));
                txtSodium.setText(res.getString(7));
                txtCarbs.setText(res.getString(8));
                txtProtein.setText(res.getString(9));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageProductsNA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblProductMouseClicked

    public void resetForm(){
    
        txtName.setText(null);
        txtRefQty.setText(null);
        txtAdd.setText(null);
        txtCalorie.setText(null);
        txtFat.setText(null);
        txtChol.setText(null);
        txtSodium.setText(null);
        txtCarbs.setText(null);
        txtProtein.setText(null);

    }
    
    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblProduct.getSelectedRow();
        model = (DefaultTableModel) tblProduct.getModel();

        String product_name = model.getValueAt(selectedRow,0).toString();

        ProductApproval product = new ProductApproval();

        product.approveProduct(product_name);

        JOptionPane.showMessageDialog(this, "Product is Approved!",
            "Product approved",JOptionPane.INFORMATION_MESSAGE);
        resetForm();
        populateTable();

    }//GEN-LAST:event_btnApproveActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        NAHomePage mf = new NAHomePage();
        mf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked
    private void populateTable() {
        ProductDirectory product = new ProductDirectory();
        ResultSet res = product.getPendingProductData();
        tblProduct.setModel(DbUtils.resultSetToTableModel(res));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageProductsNA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.ButtonGroup btnGroupDiabetes;
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPurpose2;
    private javax.swing.JLabel lblPurpose3;
    private javax.swing.JLabel lblPurpose4;
    private javax.swing.JLabel lblPurpose5;
    private javax.swing.JLabel lblPurpose6;
    private javax.swing.JLabel lblPurpose7;
    private javax.swing.JLabel lblPurpose8;
    private javax.swing.JLabel lblPurpose9;
    private javax.swing.JLabel lblWorkoutFrequency10;
    private javax.swing.JLabel lblWorkoutFrequency11;
    private javax.swing.JLabel lblWorkoutFrequency12;
    private javax.swing.JLabel lblWorkoutFrequency13;
    private javax.swing.JLabel lblWorkoutFrequency14;
    private javax.swing.JLabel lblWorkoutFrequency15;
    private javax.swing.JLabel lblWorkoutFrequency16;
    private javax.swing.JLabel lblWorkoutFrequency17;
    private javax.swing.JLabel lblWorkoutFrequency18;
    private javax.swing.JLabel lblWorkoutFrequency19;
    private javax.swing.JLabel lblWorkoutFrequency20;
    private javax.swing.JLabel lblWorkoutFrequency21;
    private javax.swing.JLabel lblWorkoutFrequency22;
    private javax.swing.JLabel lblWorkoutFrequency23;
    private javax.swing.JLabel lblWorkoutFrequency24;
    private javax.swing.JLabel lblWorkoutFrequency25;
    private javax.swing.JLabel lblWorkoutFrequency6;
    private javax.swing.JLabel lblWorkoutFrequency7;
    private javax.swing.JLabel lblWorkoutFrequency8;
    private javax.swing.JLabel lblWorkoutFrequency9;
    private javax.swing.JPanel panelDiet1;
    private javax.swing.JPanel panelDiet2;
    private javax.swing.JPanel panelDiet3;
    private javax.swing.JPanel panelDiet4;
    private javax.swing.JPanel panelDiet5;
    private javax.swing.JPanel panelDiet6;
    private javax.swing.JPanel panelDiet7;
    private javax.swing.JPanel panelDiet8;
    private javax.swing.JPanel pnlSideOptions;
    private javax.swing.JPanel pnlTitleBar;
    private javax.swing.JPanel pnlWorkArea;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtCalorie;
    private javax.swing.JTextField txtCarbs;
    private javax.swing.JTextField txtChol;
    private javax.swing.JTextField txtFat;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtProtein;
    private javax.swing.JTextField txtQualification10;
    private javax.swing.JTextField txtQualification11;
    private javax.swing.JTextField txtQualification12;
    private javax.swing.JTextField txtQualification16;
    private javax.swing.JTextField txtQualification17;
    private javax.swing.JTextField txtQualification18;
    private javax.swing.JTextField txtQualification19;
    private javax.swing.JTextField txtQualification20;
    private javax.swing.JTextField txtQualification21;
    private javax.swing.JTextField txtQualification22;
    private javax.swing.JTextField txtQualification23;
    private javax.swing.JTextField txtQualification24;
    private javax.swing.JTextField txtQualification4;
    private javax.swing.JTextField txtQualification5;
    private javax.swing.JTextField txtQualification6;
    private javax.swing.JTextField txtQualification7;
    private javax.swing.JTextField txtQualification8;
    private javax.swing.JTextField txtQualification9;
    private javax.swing.JTextField txtRefQty;
    private javax.swing.JTextField txtSodium;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
