/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.User;

import UI.SystemAdmin.ManageUsersSA;
import Model.Appointments.AppointmentDirectory;
import java.sql.Connection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import Model.Database.DBconnection;
import Model.Enterprise.Hospital.HospitalDirectory;
import Model.People.DietitianDirectory;
import Model.People.User;
import Model.People.UserDirectory;
import Model.Utilities.SendMail;
import Model.Utilities.UtilityFunctions;
import UI.Authenticate.LoginFrame;
import UI.SystemAdmin.ManageDietitiansSA;
import UI.Main.MainFrame;
import UI.SystemAdmin.SAHomePage;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.Period;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.*;
import javax.mail.MessagingException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author vipul
 */
public class UserAppointmentBooking extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    String userName;
    String email_id;
    
    private TableRowSorter sorter;
    public UserAppointmentBooking(String userName) {
        initComponents();
        this.userName = userName;
        //this.records = records;
        lblWelcome.setText("Welcome, " + this.userName);
        generateHospitalDropDown();
        
    }
    
    public UserAppointmentBooking() {
        initComponents();
        generateHospitalDropDown();
    }

    UserAppointmentBooking(String userName, String email_id) {
        initComponents();
        this.userName = userName;
        this.email_id = email_id;
        lblWelcome.setText("Welcome, " + this.userName);
        generateHospitalDropDown();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGender = new javax.swing.ButtonGroup();
        btnGroupDiabetes = new javax.swing.ButtonGroup();
        pnlTitleBar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        pnlWorkArea = new javax.swing.JPanel();
        pnlRegistration = new javax.swing.JPanel();
        panelDiet = new javax.swing.JPanel();
        comboType = new javax.swing.JComboBox<>();
        lblWorkoutFrequency2 = new javax.swing.JLabel();
        comboHospital = new javax.swing.JComboBox<>();
        lblWorkoutFrequency3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelMedical1 = new javax.swing.JPanel();
        txtDietitianName = new javax.swing.JTextField();
        lblDiabetes2 = new javax.swing.JLabel();
        lblHeight2 = new javax.swing.JLabel();
        dateAppointment = new com.toedter.calendar.JDateChooser();
        txtHospitalName = new javax.swing.JTextField();
        lblHeight3 = new javax.swing.JLabel();
        lblDiabetes3 = new javax.swing.JLabel();
        timeAppointment = new com.github.lgooddatepicker.components.TimePicker();
        btnBook = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableView = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblAppointment = new javax.swing.JLabel();
        lblDailyIntake = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblHomePage = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblAccount2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lblAccount3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblAccount1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(66, 179, 172));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTitleBar.setBackground(new java.awt.Color(100, 129, 152));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Diet Management System");
        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("X");
        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        lblWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/male_user_50px.png"))); // NOI18N
        lblWelcome.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlTitleBarLayout = new javax.swing.GroupLayout(pnlTitleBar);
        pnlTitleBar.setLayout(pnlTitleBarLayout);
        pnlTitleBarLayout.setHorizontalGroup(
            pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleBarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
        );
        pnlTitleBarLayout.setVerticalGroup(
            pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleBarLayout.createSequentialGroup()
                .addGroup(pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTitleBarLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlTitleBarLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlTitleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 60));

        pnlWorkArea.setBackground(new java.awt.Color(255, 255, 255));
        pnlWorkArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRegistration.setBackground(new java.awt.Color(255, 255, 255));
        pnlRegistration.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDiet.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Diet Related", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consultant", "Clinical", "Pediatric", "Sports", "Research" }));
        comboType.setSelectedIndex(-1);
        comboType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTypeActionPerformed(evt);
            }
        });
        panelDiet.add(comboType, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 200, 30));

        lblWorkoutFrequency2.setText("Dietitian Type");
        panelDiet.add(lblWorkoutFrequency2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        comboHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboHospitalActionPerformed(evt);
            }
        });
        panelDiet.add(comboHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, 30));

        lblWorkoutFrequency3.setText("Hospital");
        panelDiet.add(lblWorkoutFrequency3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelDiet.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 80, 30));

        pnlRegistration.add(panelDiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 770, 80));

        panelMedical1.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelMedical1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Appointment Booking", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelMedical1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDietitianName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDietitianNameKeyTyped(evt);
            }
        });
        panelMedical1.add(txtDietitianName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 200, 30));

        lblDiabetes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/dietitian/icons8-appointment-time-29.png"))); // NOI18N
        lblDiabetes2.setText("Appointment Time");
        panelMedical1.add(lblDiabetes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 140, -1));

        lblHeight2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons/icons8-name-tag-30.png"))); // NOI18N
        lblHeight2.setText("  Dietitian Name");
        panelMedical1.add(lblHeight2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, -1));
        panelMedical1.add(dateAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 200, 30));

        txtHospitalName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHospitalNameKeyTyped(evt);
            }
        });
        panelMedical1.add(txtHospitalName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 200, 30));

        lblHeight3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/hospital/icons8-hospital-29.png"))); // NOI18N
        lblHeight3.setText("  Hosital Name");
        panelMedical1.add(lblHeight3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, -1));

        lblDiabetes3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/userIcons/icons8-age-29.png"))); // NOI18N
        lblDiabetes3.setText("Appointment Date");
        panelMedical1.add(lblDiabetes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 140, -1));
        panelMedical1.add(timeAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 200, 30));

        btnBook.setText("Send Appointment Request");
        btnBook.setBackground(new java.awt.Color(255, 51, 51));
        btnBook.setForeground(new java.awt.Color(255, 255, 255));
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        panelMedical1.add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 180, 40));

        pnlRegistration.add(panelMedical1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 770, 180));

        tableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Gender", "Age", "Contact", "Hospital", "Type", "Qualification", "Experience", "Slots Available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableViewMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableView);

        pnlRegistration.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 770, 130));

        pnlWorkArea.add(pnlRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 610));

        getContentPane().add(pnlWorkArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 63, 830, 610));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(192, 202, 97));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogout.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        lblLogout.setText("   Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        jPanel6.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 190, 45));

        jPanel7.setBackground(new java.awt.Color(255, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAppointment.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        lblAppointment.setForeground(new java.awt.Color(255, 255, 255));
        lblAppointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/Icon-Small.png"))); // NOI18N
        lblAppointment.setText(" Consult a Dietitian");
        lblAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAppointmentMouseClicked(evt);
            }
        });
        jPanel7.add(lblAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, -1));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 190, 45));

        lblDailyIntake.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        lblDailyIntake.setForeground(new java.awt.Color(255, 255, 255));
        lblDailyIntake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/users_sadmin_29px.png"))); // NOI18N
        lblDailyIntake.setText(" Today's Intake");
        lblDailyIntake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDailyIntakeMouseClicked(evt);
            }
        });
        jPanel3.add(lblDailyIntake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, -1));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHomePage.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lblHomePage.setForeground(new java.awt.Color(255, 255, 255));
        lblHomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        lblHomePage.setText(" Home Page");
        lblHomePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomePageMouseClicked(evt);
            }
        });
        jPanel8.add(lblHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, -1));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 45));

        jPanel12.setBackground(new java.awt.Color(255, 51, 51));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel15.setText("  Home Page");
        jPanel12.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 45));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAccount2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        lblAccount2.setForeground(new java.awt.Color(255, 255, 255));
        lblAccount2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/Icon-Small_1.png"))); // NOI18N
        lblAccount2.setText(" Account");
        lblAccount2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccount2MouseClicked(evt);
            }
        });
        jPanel10.add(lblAccount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, -1));

        jPanel11.setBackground(new java.awt.Color(255, 51, 51));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAccount3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        lblAccount3.setForeground(new java.awt.Color(255, 255, 255));
        lblAccount3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/Icon-Small_1.png"))); // NOI18N
        lblAccount3.setText(" Account");
        lblAccount3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccount3MouseClicked(evt);
            }
        });
        jPanel11.add(lblAccount3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, -1));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, 45));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, 45));

        jPanel9.setBackground(new java.awt.Color(255, 51, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAccount1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        lblAccount1.setForeground(new java.awt.Color(255, 255, 255));
        lblAccount1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/Icon-Small_1.png"))); // NOI18N
        lblAccount1.setText(" Account");
        lblAccount1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccount1MouseClicked(evt);
            }
        });
        jPanel9.add(lblAccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, -1));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, 45));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 190, 610));

        setSize(new java.awt.Dimension(1014, 673));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void generateHospitalDropDown() {
        
        HospitalDirectory hd = new HospitalDirectory();
        List<String> hospitalList = hd.getAllHospitalsList();
        
        String[] foodDropdown = hospitalList.toArray(new String[hospitalList.size()]);
        DefaultComboBoxModel<String> yearsSDropdownModel = new DefaultComboBoxModel<>(foodDropdown);
        comboHospital.setModel(yearsSDropdownModel);
        comboHospital.setSelectedIndex(-1);
        
    }
    
    public void resetForm(){
        
         txtDietitianName.setText(null);
         txtHospitalName.setText(null);
         dateAppointment.setDate(null);
         timeAppointment.setTime(null);
    }
    
    
    
    
    public LocalDate convertToLocalDateViaInstant(Date dateToConvert) {
        return dateToConvert.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }
    
    
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setForeground(Color.red);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel3.setForeground(Color.white);
    }//GEN-LAST:event_jLabel3MouseExited

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        LoginFrame frame = new LoginFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblDailyIntakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDailyIntakeMouseClicked
        // TODO add your handling code here:
        UserDailyIntake frame = new UserDailyIntake(this.userName);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblDailyIntakeMouseClicked

    private void lblAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAppointmentMouseClicked
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_lblAppointmentMouseClicked

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:

        if(true){
            
            String dietitianName = txtDietitianName.getText();
            String hospitalName = txtHospitalName.getText();
            Date date = dateAppointment.getDate();
            LocalTime time = timeAppointment.getTime(); 
            

            String status;
            //--------------------------------------Hospital Request----------------------
            if (hospitalName.equals("NA")){
                
                AppointmentDirectory ad = new AppointmentDirectory();
                 status = "Requested";
                ad.addAppointment(this.userName, dietitianName, hospitalName, date, time, status);

                DietitianDirectory dd = new DietitianDirectory();
                dd.updateSlots(dietitianName);
                
                ResultSet res = dd.getDietitianEmailByName(dietitianName);
                String d_email = "";
                try{
                    while(res.next()){
                    
                        d_email = res.getString(1);
                    }
                }
                catch(SQLException ex){
                    Logger.getLogger(UserAppointmentBooking.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                try {
                    sendEmailTo(d_email,"Appointment Request Received!","Hi " + dietitianName + 
                        ",\nYou have received a new appointment request.\nPlease open your dashboard to accept or reject the request.");
                } catch (Exception ex) {
                    Logger.getLogger(UserAppointmentBooking.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            //--------------------------------------Hospital Request----------------------
            else{
                AppointmentDirectory ad = new AppointmentDirectory();
                 status = "Pending";
                ad.addAppointment(this.userName, dietitianName, hospitalName, date, time, status);
                
                HospitalDirectory hd = new HospitalDirectory();
                ResultSet res = hd.getHospitalEmailByName(hospitalName);
                String h_email = "";
                try{
                    while(res.next()){
                    
                        h_email = res.getString(1);
                    }
                }
                catch(SQLException ex){
                    Logger.getLogger(UserAppointmentBooking.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                try {
                    sendEmailTo(h_email,"Appointment Request Received!","Hi " + hospitalName + 
                        ",\nYou have received a new appointment request.\nPlease open your dashboard to forward it to a dietitian.");
                } catch (Exception ex) {
                    Logger.getLogger(UserAppointmentBooking.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
//            AppointmentDirectory ad = new AppointmentDirectory();
//            ad.addAppointment(this.userName, dietitianName, hospitalName, date, time, status);

            DietitianDirectory dd = new DietitianDirectory();
            dd.updateSlots(dietitianName);


            populateTableData();
            JOptionPane.showMessageDialog(this, "Appointment Requested Successfully");
            resetForm();
            try {
                sendEmailTo(email_id,"Appointment Requested!","Hi " + this.userName + ",\nYour appointment with Dietitian " 
                        + dietitianName  + " for " + date + " at " + time+ " is requested. "
                                + "You will be informed, once appointment is approved.");
            } catch (Exception ex) {
                Logger.getLogger(UserAppointmentBooking.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btnBookActionPerformed

    public void sendEmailTo(String mailto, String sub, String body) throws Exception{
        SendMail mail = new SendMail(mailto, sub, body);     
    }
    
    private void lblHomePageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomePageMouseClicked
        // TODO add your handling code here:
        UserHomePage frame = new UserHomePage(this.userName, 0);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblHomePageMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        LoginFrame fr = new LoginFrame();
        fr.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void lblAccount2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccount2MouseClicked
        // TODO add your handling code here:
        UserUpdateInfo ud = new UserUpdateInfo(this.userName);
        ud.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblAccount2MouseClicked

    private void lblAccount3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccount3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAccount3MouseClicked

    private void lblAccount1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccount1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAccount1MouseClicked

    private void comboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTypeActionPerformed

    private void txtDietitianNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDietitianNameKeyTyped
        // TODO add your handling code here:
        char typedName = evt.getKeyChar();
        if(!Character.isAlphabetic(typedName) && !Character.isWhitespace(typedName)){
            evt.consume();
        }
        //Restrict the length to 256
        if(txtDietitianName.getText().length() > 255){
            evt.consume();
        }
    }//GEN-LAST:event_txtDietitianNameKeyTyped

    private void txtHospitalNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHospitalNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalNameKeyTyped

    private void tableViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableViewMouseClicked
        // TODO add your handling code here:
        int rowIndex = tableView.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tableView.getModel();
        
        String dietitianName = String.valueOf(model.getValueAt(rowIndex,1));
        String hospital = String.valueOf(model.getValueAt(rowIndex,5));
        System.out.println("------------" + hospital );
        txtDietitianName.setText(dietitianName);
        txtHospitalName.setText(hospital);
        txtDietitianName.setEditable(false);
        txtHospitalName.setEditable(false);
        
        Date appointmentDate = dateAppointment.getDate();
        LocalTime appointmentTime = timeAppointment.getTime();
        
    }//GEN-LAST:event_tableViewMouseClicked

    private void comboHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboHospitalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        populateTableData();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    boolean isDataValid(){
//        String id, name, emailId, gender, community, city, state, username ;
//        String houseNumber, zipCode, age, bloodGroup, height, weight;
//        String contactDetails;
////        Date dob;
//        //String patternEmail = "^[A-Za-z0-9+_.-]+@(.+)$";
//        String patternEmail = "^[(a-zA-Z-0-9-\\_\\+\\.)]+@[(a-z-A-z)]+\\.[(a-zA-z)]{2,3}$";
//        String bmi = "[(0-9\\.)]{2,}$";
//               
//        id = txtDoctorID.getText();
//        name = txtName.getText();
//        emailId = txtEmail.getText();
//        contactDetails = txtContact.getText();
//        age = txtAge.getText();
////        dob = DOBtxt.getDate();
//        if(comboPurpose.getSelectedItem() == null){
//            houseNumber = "";
//        }
//        else{
//            houseNumber = comboPurpose.getSelectedItem().toString();
//        }
//        
//        
//        if(comboCommunity.getSelectedItem() == null){
//            community = "";
//        }
//        else{
//            community = comboCommunity.getSelectedItem().toString();
//        }
//        
//        
//        if(comboCity.getSelectedItem() == null){
//            city = "";
//        }
//        else{
//            city = comboCity.getSelectedItem().toString();
//        }
//        state = txtState.getText();
//        zipCode = txtZipCode.getText();
//        //bloodGroup = (String) patientBloodGroupTxt.getSelectedItem();
//        String qualification = txtQualification.getText();
//        String specialization = txtSpecialization.getText();
//        String slots = txtHeight.getText();
//        String password = new String(txtPassword.getText());
//        String rePassword = new String(txtPassword2.getPassword());
//        
//        
//       
//        if(comboGender.getSelectedItem() == null){
//            gender = "";
//        }
//        else{
//            gender = comboGender.getSelectedItem().toString(); 
//        }
//        
//        String hospital;
//        if(comboBloodGroup.getSelectedItem() == null){
//            hospital = "";
//        }
//        else{
//            hospital = comboBloodGroup.getSelectedItem().toString(); 
//        }
//        
//        
//        if (id.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter Patient ID");
//            return false;
//        }
//       
//        if (name.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter name");
//            return false;
//        }
//        
//        if (gender.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please select gender");
//            return false;
//        }
//        
//        if (hospital.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please select hospital");
//            return false;
//        }
//        
//        if (contactDetails.equals("") || !(txtContact.getText().length()==10))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter valid contact Number");
//            txtContact.setText("");
//           
//            return false;
//        }
//        //emailIDTxt.getText().isBlank() &&
//        if( !txtEmail.getText().matches(patternEmail)){
//                JOptionPane.showMessageDialog(this, "Please enter a valid Email.");
//                txtEmail.setText("");
//                return false;
//            }
//       
//        if (age.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter age");
//            return false;
//        }
//       
//        if (slots.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter number of slots available");
//            return false;
//        }
//        
//        if (qualification.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter qualification");
//            return false;
//        }
//        if (specialization.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter specialization");
//            return false;
//        }
       
       
//        if (zipCode.equals("") || !(txtZipCode.getText().length()==5))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter zipCode");
//            txtZipCode.setText("");
//            return false;
//        }
//       
//   
//       
//        if (password.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter password");
//            return false;
//        }
//       
//        if (rePassword.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter rePassword");
//            return false;
//        }
//       
//        if (!(password).equals(rePassword)){
//            JOptionPane.showMessageDialog(this, "Password doesn't match");
//            return false;
//        }
       
        return true;
       
    }
    
    private void populateTableData() {
        
        //Type-cast table model into default table model
        DefaultTableModel model = (DefaultTableModel) tableView.getModel();
        
        //Clear the table 
        model.setRowCount(0);
        
        String hospital, type;
        if(comboHospital.getSelectedIndex() == -1){
            hospital = "";
        }
        else{
            hospital = comboHospital.getSelectedItem().toString();
        }
        
        if(comboType.getSelectedIndex() == -1){
            type = "";
        }
        else{
            type = comboType.getSelectedItem().toString();
        }
        
        System.out.println(type +  hospital);
        DietitianDirectory dd = new DietitianDirectory();
        ResultSet res = dd.viewDietitians(type, hospital);
        try{
            while(res.next()){
                Object[] row = new Object[11];
                row[0] = res.getInt("ID");
                row[1] = res.getString("Name");
                row[2] = res.getString("Gender");
                row[3] = res.getInt("Age");
                row[4] = res.getLong("Contact");
                row[5] = res.getString("Hospital");
                row[6] = res.getString("Type");
                row[7] = res.getString("Qualification");
                row[8] = res.getInt("Experience");
                row[9] = res.getInt("Slots");

                model.addRow(row);
            }
        }catch(SQLException ex){
            Logger.getLogger(UserAppointmentBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAppointmentBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.ButtonGroup btnGroupDiabetes;
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.JComboBox<String> comboHospital;
    private javax.swing.JComboBox<String> comboType;
    private com.toedter.calendar.JDateChooser dateAppointment;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAccount1;
    private javax.swing.JLabel lblAccount2;
    private javax.swing.JLabel lblAccount3;
    private javax.swing.JLabel lblAppointment;
    private javax.swing.JLabel lblDailyIntake;
    private javax.swing.JLabel lblDiabetes2;
    private javax.swing.JLabel lblDiabetes3;
    private javax.swing.JLabel lblHeight2;
    private javax.swing.JLabel lblHeight3;
    private javax.swing.JLabel lblHomePage;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWorkoutFrequency2;
    private javax.swing.JLabel lblWorkoutFrequency3;
    private javax.swing.JPanel panelDiet;
    private javax.swing.JPanel panelMedical1;
    private javax.swing.JPanel pnlRegistration;
    private javax.swing.JPanel pnlTitleBar;
    private javax.swing.JPanel pnlWorkArea;
    private javax.swing.JTable tableView;
    private com.github.lgooddatepicker.components.TimePicker timeAppointment;
    private javax.swing.JTextField txtDietitianName;
    private javax.swing.JTextField txtHospitalName;
    // End of variables declaration//GEN-END:variables
}
