/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.User;

import java.sql.Connection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import Model.Database.DBconnection;
import Model.Diet.DietIntake;
import Model.Enterprise.GroceryStores.GroceryStoresDirectory;
import Model.People.User;
import Model.People.UserDirectory;
import Model.Organization.ProductDirectory;
import Model.Utilities.UtilityFunctions;
import UI.Authenticate.LoginFrame;
import UI.Main.MainFrame;
import UI.SystemAdmin.SAHomePage;
import UI.SystemAdmin.ManageGroceryStoresSA;
import java.awt.Color;
import java.io.IOException;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author vipul
 */
public class UserDailyIntake extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    String userName;
    
    private TableRowSorter sorter;
    public UserDailyIntake(String userName) {
        initComponents();
        this.userName = userName;
        //this.records = records;
        lblWelcome.setText("Welcome, " + this.userName);
        
        ProductDirectory pd = new ProductDirectory();
        List<String> foodList = pd.getAllProducts();
        generateFood1Dropdown(foodList);
        generateFood2Dropdown(foodList);
        generateFood3Dropdown(foodList);
        generateFood4Dropdown(foodList);
        showDietInfo(this.userName);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGender = new javax.swing.ButtonGroup();
        btnGroupDiabetes = new javax.swing.ButtonGroup();
        pnlTitleBar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        pnlWorkArea = new javax.swing.JPanel();
        pnlRegistration = new javax.swing.JPanel();
        panelMedical = new javax.swing.JPanel();
        comboFood4 = new javax.swing.JComboBox<>();
        comboQuantity4 = new javax.swing.JComboBox<>();
        btnAdd4 = new javax.swing.JButton();
        lblDiabetes10 = new javax.swing.JLabel();
        lblDiabetes12 = new javax.swing.JLabel();
        panelMedical1 = new javax.swing.JPanel();
        comboFood2 = new javax.swing.JComboBox<>();
        comboQuantity2 = new javax.swing.JComboBox<>();
        btnAdd2 = new javax.swing.JButton();
        lblDiabetes8 = new javax.swing.JLabel();
        lblDiabetes6 = new javax.swing.JLabel();
        panelMedical2 = new javax.swing.JPanel();
        comboFood1 = new javax.swing.JComboBox<>();
        lblDiabetes5 = new javax.swing.JLabel();
        comboQuantity1 = new javax.swing.JComboBox<>();
        btnAdd1 = new javax.swing.JButton();
        lblDiabetes2 = new javax.swing.JLabel();
        panelMedical3 = new javax.swing.JPanel();
        comboFood3 = new javax.swing.JComboBox<>();
        comboQuantity3 = new javax.swing.JComboBox<>();
        btnAdd3 = new javax.swing.JButton();
        lblDiabetes9 = new javax.swing.JLabel();
        lblDiabetes11 = new javax.swing.JLabel();
        panelMedical4 = new javax.swing.JPanel();
        lblSodium = new javax.swing.JLabel();
        lblCalories = new javax.swing.JLabel();
        lblProtein = new javax.swing.JLabel();
        lblCarbs = new javax.swing.JLabel();
        lblFats = new javax.swing.JLabel();
        lblCholesterol = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblDailyIntake = new javax.swing.JLabel();
        lblAppointment = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblHomePage = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblAccount1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(66, 179, 172));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTitleBar.setBackground(new java.awt.Color(100, 129, 152));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_menu_48px_1.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Diet Management System");

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/male_user_50px.png"))); // NOI18N

        javax.swing.GroupLayout pnlTitleBarLayout = new javax.swing.GroupLayout(pnlTitleBar);
        pnlTitleBar.setLayout(pnlTitleBarLayout);
        pnlTitleBarLayout.setHorizontalGroup(
            pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleBarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
        );
        pnlTitleBarLayout.setVerticalGroup(
            pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleBarLayout.createSequentialGroup()
                .addGroup(pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTitleBarLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlTitleBarLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlTitleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 60));

        pnlWorkArea.setBackground(new java.awt.Color(255, 255, 255));
        pnlWorkArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRegistration.setBackground(new java.awt.Color(255, 255, 255));
        pnlRegistration.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMedical.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelMedical.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Meal 4", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 14))); // NOI18N
        panelMedical.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMedical.add(comboFood4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 200, 30));

        comboQuantity4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Cup (100g)", "1.5 Cups (150g)", "2 Cups (200g)", "2.5 Cups (250g)", "3 Cups (300g)", "3.5 Cups (350g)" }));
        comboQuantity4.setSelectedIndex(-1);
        panelMedical.add(comboQuantity4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 200, 30));

        btnAdd4.setBackground(new java.awt.Color(121, 237, 39));
        btnAdd4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        btnAdd4.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd4.setText("+");
        btnAdd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd4ActionPerformed(evt);
            }
        });
        panelMedical.add(btnAdd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 50, 30));

        lblDiabetes10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/meals/icons8-meal-50.png"))); // NOI18N
        lblDiabetes10.setText("  Food Item:");
        panelMedical.add(lblDiabetes10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, -1));

        lblDiabetes12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/meals/icons8-bowl-with-spoon-50.png"))); // NOI18N
        lblDiabetes12.setText("  Quantity:");
        panelMedical.add(lblDiabetes12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 110, -1));

        pnlRegistration.add(panelMedical, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 751, 80));

        panelMedical1.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelMedical1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Meal 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 14))); // NOI18N
        panelMedical1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMedical1.add(comboFood2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 200, 30));

        comboQuantity2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Cup (100g)", "1.5 Cups (150g)", "2 Cups (200g)", "2.5 Cups (250g)", "3 Cups (300g)", "3.5 Cups (350g)" }));
        comboQuantity2.setSelectedIndex(-1);
        panelMedical1.add(comboQuantity2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 200, 30));

        btnAdd2.setBackground(new java.awt.Color(121, 237, 39));
        btnAdd2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        btnAdd2.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd2.setText("+");
        btnAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd2ActionPerformed(evt);
            }
        });
        panelMedical1.add(btnAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 50, 30));

        lblDiabetes8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/meals/icons8-meal-50.png"))); // NOI18N
        lblDiabetes8.setText("  Food Item:");
        panelMedical1.add(lblDiabetes8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 50));

        lblDiabetes6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/meals/icons8-bowl-with-spoon-50.png"))); // NOI18N
        lblDiabetes6.setText("  Quantity:");
        panelMedical1.add(lblDiabetes6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 110, -1));

        pnlRegistration.add(panelMedical1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 751, 80));

        panelMedical2.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelMedical2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Meal 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 14))); // NOI18N
        panelMedical2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMedical2.add(comboFood1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 200, 30));

        lblDiabetes5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/meals/icons8-bowl-with-spoon-50.png"))); // NOI18N
        lblDiabetes5.setText("  Quantity:");
        panelMedical2.add(lblDiabetes5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 110, -1));

        comboQuantity1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Cup (100g)", "1.5 Cups (150g)", "2 Cups (200g)", "2.5 Cups (250g)", "3 Cups (300g)", "3.5 Cups (350g)" }));
        comboQuantity1.setSelectedIndex(-1);
        panelMedical2.add(comboQuantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 200, 30));

        btnAdd1.setBackground(new java.awt.Color(121, 237, 39));
        btnAdd1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        btnAdd1.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd1.setText("+");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        panelMedical2.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 50, 30));

        lblDiabetes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/meals/icons8-meal-50.png"))); // NOI18N
        lblDiabetes2.setText("  Food Item:");
        panelMedical2.add(lblDiabetes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, -1));

        pnlRegistration.add(panelMedical2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 751, 80));

        panelMedical3.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelMedical3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Meal 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 14))); // NOI18N
        panelMedical3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMedical3.add(comboFood3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 200, 30));

        comboQuantity3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Cup (100g)", "1.5 Cups (150g)", "2 Cups (200g)", "2.5 Cups (250g)", "3 Cups (300g)", "3.5 Cups (350g)" }));
        comboQuantity3.setSelectedIndex(-1);
        comboQuantity3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboQuantity3ActionPerformed(evt);
            }
        });
        panelMedical3.add(comboQuantity3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 200, 30));

        btnAdd3.setBackground(new java.awt.Color(121, 237, 39));
        btnAdd3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        btnAdd3.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd3.setText("+");
        btnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd3ActionPerformed(evt);
            }
        });
        panelMedical3.add(btnAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 50, 30));

        lblDiabetes9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/meals/icons8-meal-50.png"))); // NOI18N
        lblDiabetes9.setText("  Food Item:");
        panelMedical3.add(lblDiabetes9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, -1));

        lblDiabetes11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/meals/icons8-bowl-with-spoon-50.png"))); // NOI18N
        lblDiabetes11.setText("  Quantity:");
        panelMedical3.add(lblDiabetes11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 110, -1));

        pnlRegistration.add(panelMedical3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 751, 80));

        panelMedical4.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelMedical4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelMedical4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSodium.setBackground(new java.awt.Color(255, 255, 255));
        lblSodium.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblSodium.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sodium", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N
        panelMedical4.add(lblSodium, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 120, 70));

        lblCalories.setBackground(new java.awt.Color(255, 255, 255));
        lblCalories.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblCalories.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calories", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N
        panelMedical4.add(lblCalories, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 70));

        lblProtein.setBackground(new java.awt.Color(255, 255, 255));
        lblProtein.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblProtein.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Protein", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N
        panelMedical4.add(lblProtein, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 100, 70));

        lblCarbs.setBackground(new java.awt.Color(255, 255, 255));
        lblCarbs.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblCarbs.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carbs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N
        panelMedical4.add(lblCarbs, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 100, 70));

        lblFats.setBackground(new java.awt.Color(255, 255, 255));
        lblFats.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblFats.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fats", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N
        panelMedical4.add(lblFats, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 100, 70));

        lblCholesterol.setBackground(new java.awt.Color(255, 255, 255));
        lblCholesterol.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblCholesterol.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cholesterol", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N
        panelMedical4.add(lblCholesterol, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 120, 70));

        pnlRegistration.add(panelMedical4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 750, 100));

        lblTitle.setFont(new java.awt.Font("Segoe UI Semibold", 3, 16)); // NOI18N
        lblTitle.setText("Here are your consumption facts for today!");
        pnlRegistration.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 320, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clear Todays Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlRegistration.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 13, 160, 40));

        pnlWorkArea.add(pnlRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 610));

        getContentPane().add(pnlWorkArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 63, 830, 610));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(192, 202, 97));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        lblLogout.setText("   Logout");
        lblLogout.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        jPanel6.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 190, 45));

        jPanel7.setBackground(new java.awt.Color(255, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDailyIntake.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        lblDailyIntake.setForeground(new java.awt.Color(255, 255, 255));
        lblDailyIntake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/users_sadmin_29px.png"))); // NOI18N
        lblDailyIntake.setText(" Today's Intake");
        lblDailyIntake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDailyIntakeMouseClicked(evt);
            }
        });
        jPanel7.add(lblDailyIntake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, -1));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 190, 45));

        lblAppointment.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        lblAppointment.setForeground(new java.awt.Color(255, 255, 255));
        lblAppointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/Icon-Small.png"))); // NOI18N
        lblAppointment.setText(" Consult a Dietitian");
        lblAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAppointmentMouseClicked(evt);
            }
        });
        jPanel3.add(lblAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, -1));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHomePage.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lblHomePage.setForeground(new java.awt.Color(255, 255, 255));
        lblHomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        lblHomePage.setText(" Home Page");
        lblHomePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomePageMouseClicked(evt);
            }
        });
        jPanel8.add(lblHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, -1));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 45));

        jPanel12.setBackground(new java.awt.Color(255, 51, 51));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel15.setText("  Home Page");
        jPanel12.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 45));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAccount1.setBackground(new java.awt.Color(51, 51, 51));
        lblAccount1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        lblAccount1.setForeground(new java.awt.Color(255, 255, 255));
        lblAccount1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/Icon-Small_1.png"))); // NOI18N
        lblAccount1.setText(" Account");
        lblAccount1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccount1MouseClicked(evt);
            }
        });
        jPanel9.add(lblAccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, -1));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 185, 190, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 190, 610));

        setSize(new java.awt.Dimension(1014, 673));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    

    
    public void resetForm(){
        
        comboFood1.setSelectedIndex(-1);
        comboFood2.setSelectedIndex(-1);
        comboFood3.setSelectedIndex(-1);
        comboFood4.setSelectedIndex(-1);
        
        comboQuantity1.setSelectedIndex(-1);
        comboQuantity2.setSelectedIndex(-1);
        comboQuantity3.setSelectedIndex(-1);
        comboQuantity4.setSelectedIndex(-1);
    }
    
    
    public LocalDate convertToLocalDateViaInstant(Date dateToConvert) {
        return dateToConvert.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }
    
    
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setForeground(Color.red);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel3.setForeground(Color.white);
    }//GEN-LAST:event_jLabel3MouseExited

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        LoginFrame frame = new LoginFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblDailyIntakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDailyIntakeMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblDailyIntakeMouseClicked

    private void lblAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAppointmentMouseClicked
        // TODO add your handling code here:
        UserAppointmentBooking fr = new UserAppointmentBooking(this.userName);
        fr.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_lblAppointmentMouseClicked

    private void lblHomePageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomePageMouseClicked
        // TODO add your handling code here:
        UserHomePage frame = null;
        frame = new UserHomePage(this.userName, 0);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblHomePageMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        LoginFrame fr = new LoginFrame();
        fr.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void lblAccount1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccount1MouseClicked
        // TODO add your handling code here:
        UserUpdateInfo fr = new UserUpdateInfo(this.userName);
        fr.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblAccount1MouseClicked
    
    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:
        
        String item = comboFood1.getSelectedItem().toString();
        String quantity = comboQuantity1.getSelectedItem().toString();
        float qty = convertQuantityStringToFloat(quantity);
        System.out.println(qty);
        
        float calories = 0, protein = 0, carbs = 0, fats = 0, sodium = 0, cholesterol = 0;
        try {
            
            ProductDirectory pd = new ProductDirectory();

            ResultSet res = pd.exactNutritionLookup(item);
//        System.out.print(res + "YYYY");
            while(res.next()){
                
                calories = (qty * res.getFloat("perc_calories"))/100;
                protein = (qty * res.getFloat("perc_protein"))/100;
                carbs = (qty * res.getFloat("perc_carbs"))/100;
                fats = (qty * res.getFloat("perc_fats"))/100;   
                sodium = (qty * res.getFloat("perc_sodium"))/100;
                cholesterol = (qty * res.getFloat("perc_cholesterol"))/100; 
                System.out.println("@@@@");
                System.out.println(calories);
            }
        } catch (SQLException ex) {
            System.out.println("perc calc failed");
            Logger.getLogger(UserDailyIntake.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        updateDailyIntakeTable(calories, protein, carbs, fats, sodium, cholesterol);
        
        
        showDietInfo(this.userName);
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd2ActionPerformed
        // TODO add your handling code here:
        String item = comboFood2.getSelectedItem().toString();
        String quantity = comboQuantity2.getSelectedItem().toString();
        float qty = convertQuantityStringToFloat(quantity);
        System.out.println(qty);
        
        float calories = 0, protein = 0, carbs = 0, fats = 0, sodium = 0, cholesterol = 0;
        try {
            
            ProductDirectory pd = new ProductDirectory();

            ResultSet res = pd.exactNutritionLookup(item);
//        System.out.print(res + "YYYY");
            while(res.next()){
                
                calories = (qty * res.getFloat("perc_calories"))/100;
                protein = (qty * res.getFloat("perc_protein"))/100;
                carbs = (qty * res.getFloat("perc_carbs"))/100;
                fats = (qty * res.getFloat("perc_fats"))/100;   
                sodium = (qty * res.getFloat("perc_sodium"))/100;
                cholesterol = (qty * res.getFloat("perc_cholesterol"))/100; 
                System.out.println("@@@@");
                System.out.println(calories);
            }
        } catch (SQLException ex) {
            System.out.println("perc calc failed");
            Logger.getLogger(UserDailyIntake.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        updateDailyIntakeTable(calories, protein, carbs, fats, sodium, cholesterol);
        
        
        showDietInfo(this.userName);
    }//GEN-LAST:event_btnAdd2ActionPerformed

    private void btnAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd3ActionPerformed
        // TODO add your handling code here:
        String item = comboFood3.getSelectedItem().toString();
        String quantity = comboQuantity3.getSelectedItem().toString();
        float qty = convertQuantityStringToFloat(quantity);
        System.out.println(qty);
        
        float calories = 0, protein = 0, carbs = 0, fats = 0, sodium = 0, cholesterol = 0;
        try {
            
            ProductDirectory pd = new ProductDirectory();

            ResultSet res = pd.exactNutritionLookup(item);
//        System.out.print(res + "YYYY");
            while(res.next()){
                
                calories = (qty * res.getFloat("perc_calories"))/100;
                protein = (qty * res.getFloat("perc_protein"))/100;
                carbs = (qty * res.getFloat("perc_carbs"))/100;
                fats = (qty * res.getFloat("perc_fats"))/100;   
                sodium = (qty * res.getFloat("perc_sodium"))/100;
                cholesterol = (qty * res.getFloat("perc_cholesterol"))/100; 
                System.out.println("@@@@");
                System.out.println(calories);
            }
        } catch (SQLException ex) {
            System.out.println("perc calc failed");
            Logger.getLogger(UserDailyIntake.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        updateDailyIntakeTable(calories, protein, carbs, fats, sodium, cholesterol);
        
        
        showDietInfo(this.userName);
    }//GEN-LAST:event_btnAdd3ActionPerformed

    private void btnAdd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd4ActionPerformed
        // TODO add your handling code here:
        String item = comboFood4.getSelectedItem().toString();
        String quantity = comboQuantity4.getSelectedItem().toString();
        float qty = convertQuantityStringToFloat(quantity);
        System.out.println(qty);
        
        float calories = 0, protein = 0, carbs = 0, fats = 0, sodium = 0, cholesterol = 0;
        try {
            
            ProductDirectory pd = new ProductDirectory();

            ResultSet res = pd.exactNutritionLookup(item);
//        System.out.print(res + "YYYY");
            while(res.next()){
                
                calories = (qty * res.getFloat("perc_calories"))/100;
                protein = (qty * res.getFloat("perc_protein"))/100;
                carbs = (qty * res.getFloat("perc_carbs"))/100;
                fats = (qty * res.getFloat("perc_fats"))/100;   
                sodium = (qty * res.getFloat("perc_sodium"))/100;
                cholesterol = (qty * res.getFloat("perc_cholesterol"))/100; 
                
                System.out.println("@@@@");
                System.out.println(calories);
            }
        } catch (SQLException ex) {
            System.out.println("perc calc failed");
            Logger.getLogger(UserDailyIntake.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        updateDailyIntakeTable(calories, protein, carbs, fats, sodium, cholesterol);
        
        
        showDietInfo(this.userName);
    }//GEN-LAST:event_btnAdd4ActionPerformed

    private void comboQuantity3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboQuantity3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboQuantity3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DietIntake di = new DietIntake();
        di.resetRecordsByUser(this.userName);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void updateDailyIntakeTable(float calories, float protein,float carbs,float fats,float sodium,float cholesterol){
        
        DietIntake di = new DietIntake();
        di.updateRecordsByUser(calories,  protein, carbs, fats, sodium, cholesterol, this.userName);
        
    
    }
    public void showDietInfo(String name){
        
        DietIntake di = new DietIntake();
        ResultSet res = di.selectRecordsByUser( this.userName);
        
        try{
            
            while(res.next()){
                lblCalories.setText(res.getString("calories"));
                lblProtein.setText(res.getString("protein"));
                lblCarbs.setText(res.getString("carbs"));
                lblFats.setText(res.getString("fats"));
                lblSodium.setText(res.getString("sodium"));
                lblCholesterol.setText(res.getString("cholesterol"));
                
            }
            System.out.println(this.userName);
            
        }
        catch(SQLException ex){
            Logger.getLogger(UserDailyIntake.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    boolean isDataValid(){
//        String id, name, emailId, gender, community, city, state, username ;
//        String houseNumber, zipCode, age, bloodGroup, height, weight;
//        String contactDetails;
////        Date dob;
//        //String patternEmail = "^[A-Za-z0-9+_.-]+@(.+)$";
//        String patternEmail = "^[(a-zA-Z-0-9-\\_\\+\\.)]+@[(a-z-A-z)]+\\.[(a-zA-z)]{2,3}$";
//        String bmi = "[(0-9\\.)]{2,}$";
//               
//        id = txtDoctorID.getText();
//        name = txtName.getText();
//        emailId = txtEmail.getText();
//        contactDetails = txtContact.getText();
//        age = txtAge.getText();
////        dob = DOBtxt.getDate();
//        if(comboPurpose.getSelectedItem() == null){
//            houseNumber = "";
//        }
//        else{
//            houseNumber = comboPurpose.getSelectedItem().toString();
//        }
//        
//        
//        if(comboCommunity.getSelectedItem() == null){
//            community = "";
//        }
//        else{
//            community = comboCommunity.getSelectedItem().toString();
//        }
//        
//        
//        if(comboCity.getSelectedItem() == null){
//            city = "";
//        }
//        else{
//            city = comboCity.getSelectedItem().toString();
//        }
//        state = txtState.getText();
//        zipCode = txtZipCode.getText();
//        //bloodGroup = (String) patientBloodGroupTxt.getSelectedItem();
//        String qualification = txtQualification.getText();
//        String specialization = txtSpecialization.getText();
//        String slots = txtHeight.getText();
//        String password = new String(txtPassword.getText());
//        String rePassword = new String(txtPassword2.getPassword());
//        
//        
//       
//        if(comboGender.getSelectedItem() == null){
//            gender = "";
//        }
//        else{
//            gender = comboGender.getSelectedItem().toString(); 
//        }
//        
//        String hospital;
//        if(comboBloodGroup.getSelectedItem() == null){
//            hospital = "";
//        }
//        else{
//            hospital = comboBloodGroup.getSelectedItem().toString(); 
//        }
//        
//        
//        if (id.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter Patient ID");
//            return false;
//        }
//       
//        if (name.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter name");
//            return false;
//        }
//        
//        if (gender.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please select gender");
//            return false;
//        }
//        
//        if (hospital.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please select hospital");
//            return false;
//        }
//        
//        if (contactDetails.equals("") || !(txtContact.getText().length()==10))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter valid contact Number");
//            txtContact.setText("");
//           
//            return false;
//        }
//        //emailIDTxt.getText().isBlank() &&
//        if( !txtEmail.getText().matches(patternEmail)){
//                JOptionPane.showMessageDialog(this, "Please enter a valid Email.");
//                txtEmail.setText("");
//                return false;
//            }
//       
//        if (age.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter age");
//            return false;
//        }
//       
//        if (slots.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter number of slots available");
//            return false;
//        }
//        
//        if (qualification.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter qualification");
//            return false;
//        }
//        if (specialization.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter specialization");
//            return false;
//        }
       
       
//        if (zipCode.equals("") || !(txtZipCode.getText().length()==5))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter zipCode");
//            txtZipCode.setText("");
//            return false;
//        }
//       
//   
//       
//        if (password.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter password");
//            return false;
//        }
//       
//        if (rePassword.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter rePassword");
//            return false;
//        }
//       
//        if (!(password).equals(rePassword)){
//            JOptionPane.showMessageDialog(this, "Password doesn't match");
//            return false;
//        }
       
        return true;
       
    }
    
    public float convertQuantityStringToFloat(String qty){
        float qtyFloat = 0;
        Connection dbconn = DBconnection.connectDB();
            PreparedStatement st;
        
        try{
            String query = "SELECT quantity_gm from quantitymapping WHERE measure=?";
            st = (PreparedStatement)dbconn.prepareStatement(query);
            st.setString(1, qty); 
            ResultSet res = st.executeQuery();
            while(res.next()){
                qtyFloat = res.getFloat("quantity_gm");
                System.out.println("inside" + qtyFloat);
            }
        }
        catch(SQLException ex){
            Logger.getLogger(UserDailyIntake.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("----" + qtyFloat);
        return qtyFloat;   
    }
    
    public void generateFood1Dropdown(List<String> foodList) {
        
        String[] foodDropdown = foodList.toArray(new String[foodList.size()]);
        DefaultComboBoxModel<String> yearsSDropdownModel = new DefaultComboBoxModel<>(foodDropdown);
        comboFood1.setModel(yearsSDropdownModel);
        comboFood1.setSelectedIndex(-1);
        
    }
    
    public void generateFood2Dropdown(List<String> foodList) {
        
        String[] foodDropdown = foodList.toArray(new String[foodList.size()]);
        DefaultComboBoxModel<String> yearsSDropdownModel = new DefaultComboBoxModel<>(foodDropdown);
        comboFood2.setModel(yearsSDropdownModel);
        comboFood2.setSelectedIndex(-1);
        
    }
    
    public void generateFood3Dropdown(List<String> foodList) {
        
        String[] foodDropdown = foodList.toArray(new String[foodList.size()]);
        DefaultComboBoxModel<String> yearsSDropdownModel = new DefaultComboBoxModel<>(foodDropdown);
        comboFood3.setModel(yearsSDropdownModel);
        comboFood3.setSelectedIndex(-1);
        
    }
    
    
    public void generateFood4Dropdown(List<String> foodList) {
        
        String[] foodDropdown = foodList.toArray(new String[foodList.size()]);
        DefaultComboBoxModel<String> yearsSDropdownModel = new DefaultComboBoxModel<>(foodDropdown);
        comboFood4.setModel(yearsSDropdownModel);
        comboFood4.setSelectedIndex(-1);
        
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UserUpdateInfo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnAdd2;
    private javax.swing.JButton btnAdd3;
    private javax.swing.JButton btnAdd4;
    private javax.swing.ButtonGroup btnGroupDiabetes;
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.JComboBox<String> comboFood1;
    private javax.swing.JComboBox<String> comboFood2;
    private javax.swing.JComboBox<String> comboFood3;
    private javax.swing.JComboBox<String> comboFood4;
    private javax.swing.JComboBox<String> comboQuantity1;
    private javax.swing.JComboBox<String> comboQuantity2;
    private javax.swing.JComboBox<String> comboQuantity3;
    private javax.swing.JComboBox<String> comboQuantity4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblAccount1;
    private javax.swing.JLabel lblAppointment;
    private javax.swing.JLabel lblCalories;
    private javax.swing.JLabel lblCarbs;
    private javax.swing.JLabel lblCholesterol;
    private javax.swing.JLabel lblDailyIntake;
    private javax.swing.JLabel lblDiabetes10;
    private javax.swing.JLabel lblDiabetes11;
    private javax.swing.JLabel lblDiabetes12;
    private javax.swing.JLabel lblDiabetes2;
    private javax.swing.JLabel lblDiabetes5;
    private javax.swing.JLabel lblDiabetes6;
    private javax.swing.JLabel lblDiabetes8;
    private javax.swing.JLabel lblDiabetes9;
    private javax.swing.JLabel lblFats;
    private javax.swing.JLabel lblHomePage;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblProtein;
    private javax.swing.JLabel lblSodium;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel panelMedical;
    private javax.swing.JPanel panelMedical1;
    private javax.swing.JPanel panelMedical2;
    private javax.swing.JPanel panelMedical3;
    private javax.swing.JPanel panelMedical4;
    private javax.swing.JPanel pnlRegistration;
    private javax.swing.JPanel pnlTitleBar;
    private javax.swing.JPanel pnlWorkArea;
    // End of variables declaration//GEN-END:variables
}
