/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.MealService;

import Model.WorkRequest.ProductApproval;
import Model.Organization.ProductDirectory;
import UI.Authenticate.LoginFrame;
import UI.GroceryStore.GSManageProduct;
import UI.SystemAdmin.ManageUsersSA;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author naman
 */
public class MSManageProduct extends javax.swing.JFrame {
    DefaultTableModel model;
    public String name;
    /**
     * Creates new form SAHomePage
     * @param name
     */
    public MSManageProduct(String name) {
        initComponents();
        this.name = name;
        populateTable("");
    }
    
    public MSManageProduct() {
        initComponents();
        populateTable("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        panelControl = new javax.swing.JPanel();
        panellGreen = new javax.swing.JPanel();
        panelLogout = new javax.swing.JLabel();
        panelRed = new javax.swing.JPanel();
        panelProducts = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        pnlRegistration = new javax.swing.JPanel();
        panelMedical = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        lblHeight = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        lblAllergies2 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        panelDiet2 = new javax.swing.JPanel();
        lblPurpose3 = new javax.swing.JLabel();
        lblWorkoutFrequency10 = new javax.swing.JLabel();
        txtRefQty = new javax.swing.JTextField();
        lblWorkoutFrequency11 = new javax.swing.JLabel();
        txtCarbs = new javax.swing.JTextField();
        txtCalorie = new javax.swing.JTextField();
        panelDiet3 = new javax.swing.JPanel();
        lblPurpose4 = new javax.swing.JLabel();
        lblWorkoutFrequency12 = new javax.swing.JLabel();
        txtQualification4 = new javax.swing.JTextField();
        lblWorkoutFrequency13 = new javax.swing.JLabel();
        txtQualification5 = new javax.swing.JTextField();
        txtQualification6 = new javax.swing.JTextField();
        panelDiet4 = new javax.swing.JPanel();
        lblPurpose5 = new javax.swing.JLabel();
        lblWorkoutFrequency14 = new javax.swing.JLabel();
        txtQualification7 = new javax.swing.JTextField();
        lblWorkoutFrequency15 = new javax.swing.JLabel();
        txtQualification8 = new javax.swing.JTextField();
        txtQualification9 = new javax.swing.JTextField();
        panelDiet5 = new javax.swing.JPanel();
        lblPurpose6 = new javax.swing.JLabel();
        lblWorkoutFrequency16 = new javax.swing.JLabel();
        txtQualification10 = new javax.swing.JTextField();
        lblWorkoutFrequency17 = new javax.swing.JLabel();
        txtQualification11 = new javax.swing.JTextField();
        txtQualification12 = new javax.swing.JTextField();
        txtFat = new javax.swing.JTextField();
        lblWorkoutFrequency22 = new javax.swing.JLabel();
        txtChol = new javax.swing.JTextField();
        lblWorkoutFrequency23 = new javax.swing.JLabel();
        lblWorkoutFrequency24 = new javax.swing.JLabel();
        txtProtein = new javax.swing.JTextField();
        lblWorkoutFrequency25 = new javax.swing.JLabel();
        txtSodium = new javax.swing.JTextField();
        pnlView = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduct1 = new javax.swing.JTable();
        panelMedical2 = new javax.swing.JPanel();
        txtName2 = new javax.swing.JTextField();
        txtType1 = new javax.swing.JTextField();
        lblHeight2 = new javax.swing.JLabel();
        lblAllergies4 = new javax.swing.JLabel();
        panelDiet6 = new javax.swing.JPanel();
        txtRefQty1 = new javax.swing.JTextField();
        txtCarbs1 = new javax.swing.JTextField();
        txtCalorie1 = new javax.swing.JTextField();
        panelDiet7 = new javax.swing.JPanel();
        lblPurpose8 = new javax.swing.JLabel();
        lblWorkoutFrequency20 = new javax.swing.JLabel();
        txtQualification13 = new javax.swing.JTextField();
        lblWorkoutFrequency21 = new javax.swing.JLabel();
        txtQualification14 = new javax.swing.JTextField();
        txtQualification15 = new javax.swing.JTextField();
        panelDiet8 = new javax.swing.JPanel();
        lblPurpose9 = new javax.swing.JLabel();
        lblWorkoutFrequency26 = new javax.swing.JLabel();
        txtQualification16 = new javax.swing.JTextField();
        lblWorkoutFrequency27 = new javax.swing.JLabel();
        txtQualification17 = new javax.swing.JTextField();
        txtQualification18 = new javax.swing.JTextField();
        panelDiet9 = new javax.swing.JPanel();
        lblPurpose10 = new javax.swing.JLabel();
        lblWorkoutFrequency28 = new javax.swing.JLabel();
        txtQualification19 = new javax.swing.JTextField();
        lblWorkoutFrequency29 = new javax.swing.JLabel();
        txtQualification20 = new javax.swing.JTextField();
        txtQualification21 = new javax.swing.JTextField();
        txtFat1 = new javax.swing.JTextField();
        txtChol1 = new javax.swing.JTextField();
        txtProtein1 = new javax.swing.JTextField();
        txtSodium1 = new javax.swing.JTextField();
        lblWorkoutFrequency18 = new javax.swing.JLabel();
        lblWorkoutFrequency30 = new javax.swing.JLabel();
        lblWorkoutFrequency31 = new javax.swing.JLabel();
        lblWorkoutFrequency32 = new javax.swing.JLabel();
        lblWorkoutFrequency19 = new javax.swing.JLabel();
        lblWorkoutFrequency33 = new javax.swing.JLabel();
        lblPurpose7 = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTop.setBackground(new java.awt.Color(100, 129, 152));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_menu_48px_1.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel4.setText("Welcome");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Diet Management System");

        lblClose.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblClose)
                .addGap(18, 18, 18))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTopLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTopLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClose)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 60));

        panelControl.setBackground(new java.awt.Color(51, 51, 51));
        panelControl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panellGreen.setBackground(new java.awt.Color(192, 202, 97));
        panellGreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogout.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        panelLogout.setForeground(new java.awt.Color(255, 255, 255));
        panelLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        panelLogout.setText("   Logout");
        panelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLogoutMouseClicked(evt);
            }
        });
        panellGreen.add(panelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, -1));

        panelControl.add(panellGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 190, 45));

        panelRed.setBackground(new java.awt.Color(255, 51, 51));

        panelProducts.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        panelProducts.setForeground(new java.awt.Color(255, 255, 255));
        panelProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/product_sadmin_29px.png"))); // NOI18N
        panelProducts.setText(" Manage Products");
        panelProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelProductsMouseClicked(evt);
            }
        });
        panelProducts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelProductsKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelRedLayout = new javax.swing.GroupLayout(panelRed);
        panelRed.setLayout(panelRedLayout);
        panelRedLayout.setHorizontalGroup(
            panelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
            .addGroup(panelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRedLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelRedLayout.setVerticalGroup(
            panelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(panelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRedLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelProducts)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelControl.add(panelRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 190, 45));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel6.setText("  Home Page");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        panelControl.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, -1));

        getContentPane().add(panelControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 190, 580));

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabbedPane.setBackground(new java.awt.Color(255, 51, 51));
        tabbedPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabbedPane.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        tabbedPane.setName(""); // NOI18N

        pnlRegistration.setBackground(new java.awt.Color(255, 255, 255));

        panelMedical.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelMedical.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Meal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelMedical.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });
        panelMedical.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 200, 30));

        lblHeight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mealservice/icons8-bread-and-rye-29.png"))); // NOI18N
        lblHeight.setText("Product Name");
        panelMedical.add(lblHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, -1));

        txtType.setEditable(false);
        txtType.setText("Meal Plan Product");
        txtType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTypeKeyTyped(evt);
            }
        });
        panelMedical.add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 190, 30));

        lblAllergies2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mealservice/icons8-add-basket-29.png"))); // NOI18N
        lblAllergies2.setText("       Product Type");
        panelMedical.add(lblAllergies2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 130, -1));

        btnRegister.setBackground(new java.awt.Color(255, 51, 51));
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 51, 51));
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        panelDiet2.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nutritional Facts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPurpose3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mealservice/icons8-industrial-scales-connected-29.png"))); // NOI18N
        lblPurpose3.setText("Reference Quantity");
        panelDiet2.add(lblPurpose3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        lblWorkoutFrequency10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mealservice/icons8-calories-29.png"))); // NOI18N
        lblWorkoutFrequency10.setText("       Calorie");
        panelDiet2.add(lblWorkoutFrequency10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtRefQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRefQtyKeyTyped(evt);
            }
        });
        panelDiet2.add(txtRefQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 200, 30));

        lblWorkoutFrequency11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mealservice/icons8-carbohydrates-29.png"))); // NOI18N
        lblWorkoutFrequency11.setText("Carbohydrates");
        panelDiet2.add(lblWorkoutFrequency11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        txtCarbs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCarbsKeyTyped(evt);
            }
        });
        panelDiet2.add(txtCarbs, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 200, 30));

        txtCalorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalorieActionPerformed(evt);
            }
        });
        txtCalorie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCalorieKeyTyped(evt);
            }
        });
        panelDiet2.add(txtCalorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        panelDiet3.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nutritional Facts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPurpose4.setText("Product Name");
        panelDiet3.add(lblPurpose4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblWorkoutFrequency12.setText("Type");
        panelDiet3.add(lblWorkoutFrequency12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txtQualification4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification4KeyTyped(evt);
            }
        });
        panelDiet3.add(txtQualification4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 200, 30));

        lblWorkoutFrequency13.setText("Added By");
        panelDiet3.add(lblWorkoutFrequency13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        txtQualification5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification5KeyTyped(evt);
            }
        });
        panelDiet3.add(txtQualification5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 200, 70));

        txtQualification6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification6KeyTyped(evt);
            }
        });
        panelDiet3.add(txtQualification6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        panelDiet2.add(panelDiet3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 770, 150));

        panelDiet4.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nutritional Facts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPurpose5.setText("Product Name");
        panelDiet4.add(lblPurpose5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblWorkoutFrequency14.setText("Type");
        panelDiet4.add(lblWorkoutFrequency14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txtQualification7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification7KeyTyped(evt);
            }
        });
        panelDiet4.add(txtQualification7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 200, 30));

        lblWorkoutFrequency15.setText("Added By");
        panelDiet4.add(lblWorkoutFrequency15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        txtQualification8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification8KeyTyped(evt);
            }
        });
        panelDiet4.add(txtQualification8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 200, 70));

        txtQualification9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification9KeyTyped(evt);
            }
        });
        panelDiet4.add(txtQualification9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        panelDiet5.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nutritional Facts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPurpose6.setText("Product Name");
        panelDiet5.add(lblPurpose6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblWorkoutFrequency16.setText("Type");
        panelDiet5.add(lblWorkoutFrequency16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txtQualification10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification10KeyTyped(evt);
            }
        });
        panelDiet5.add(txtQualification10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 200, 30));

        lblWorkoutFrequency17.setText("Added By");
        panelDiet5.add(lblWorkoutFrequency17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        txtQualification11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification11KeyTyped(evt);
            }
        });
        panelDiet5.add(txtQualification11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 200, 70));

        txtQualification12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification12KeyTyped(evt);
            }
        });
        panelDiet5.add(txtQualification12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        panelDiet4.add(panelDiet5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 770, 150));

        panelDiet2.add(panelDiet4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 770, 150));

        txtFat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFatKeyTyped(evt);
            }
        });
        panelDiet2.add(txtFat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, 30));

        lblWorkoutFrequency22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mealservice/icons8-fast-food-drive-thru-29.png"))); // NOI18N
        lblWorkoutFrequency22.setText("    Total Fat");
        panelDiet2.add(lblWorkoutFrequency22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, -1));

        txtChol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCholKeyTyped(evt);
            }
        });
        panelDiet2.add(txtChol, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, 30));

        lblWorkoutFrequency23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mealservice/icons8-low-cholesterol-food-29.png"))); // NOI18N
        lblWorkoutFrequency23.setText("Cholesterol");
        panelDiet2.add(lblWorkoutFrequency23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, -1));

        lblWorkoutFrequency24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mealservice/icons8-protein-29.png"))); // NOI18N
        lblWorkoutFrequency24.setText("            Protein");
        panelDiet2.add(lblWorkoutFrequency24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        txtProtein.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProteinKeyTyped(evt);
            }
        });
        panelDiet2.add(txtProtein, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 200, 30));

        lblWorkoutFrequency25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mealservice/icons8-low-salt-29.png"))); // NOI18N
        lblWorkoutFrequency25.setText("           Sodium");
        panelDiet2.add(lblWorkoutFrequency25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        txtSodium.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSodiumKeyTyped(evt);
            }
        });
        panelDiet2.add(txtSodium, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 200, 30));

        javax.swing.GroupLayout pnlRegistrationLayout = new javax.swing.GroupLayout(pnlRegistration);
        pnlRegistration.setLayout(pnlRegistrationLayout);
        pnlRegistrationLayout.setHorizontalGroup(
            pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistrationLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelMedical, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDiet2, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(pnlRegistrationLayout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlRegistrationLayout.setVerticalGroup(
            pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrationLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(panelMedical, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(panelDiet2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(196, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Registration", pnlRegistration);

        pnlView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        pnlView.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 318, 30));

        btnUpdate.setBackground(new java.awt.Color(255, 51, 51));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlView.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 102, 35));

        tblProduct1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Product Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduct1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProduct1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProduct1);

        pnlView.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 720, 130));

        panelMedical2.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelMedical2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Meal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelMedical2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtName2KeyTyped(evt);
            }
        });
        panelMedical2.add(txtName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 200, 30));

        txtType1.setEditable(false);
        txtType1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtType1KeyTyped(evt);
            }
        });
        panelMedical2.add(txtType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 190, 30));

        lblHeight2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mealservice/icons8-bread-and-rye-29.png"))); // NOI18N
        lblHeight2.setText("Product Name");
        panelMedical2.add(lblHeight2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, -1));

        lblAllergies4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mealservice/icons8-add-basket-29.png"))); // NOI18N
        lblAllergies4.setText("       Product Type");
        panelMedical2.add(lblAllergies4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 130, -1));

        pnlView.add(panelMedical2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 751, 80));

        panelDiet6.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nutritional Facts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRefQty1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRefQty1KeyTyped(evt);
            }
        });
        panelDiet6.add(txtRefQty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 200, 30));

        txtCarbs1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCarbs1KeyTyped(evt);
            }
        });
        panelDiet6.add(txtCarbs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 200, 30));

        txtCalorie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalorie1ActionPerformed(evt);
            }
        });
        txtCalorie1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCalorie1KeyTyped(evt);
            }
        });
        panelDiet6.add(txtCalorie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        panelDiet7.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nutritional Facts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPurpose8.setText("Product Name");
        panelDiet7.add(lblPurpose8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblWorkoutFrequency20.setText("Type");
        panelDiet7.add(lblWorkoutFrequency20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txtQualification13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification13KeyTyped(evt);
            }
        });
        panelDiet7.add(txtQualification13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 200, 30));

        lblWorkoutFrequency21.setText("Added By");
        panelDiet7.add(lblWorkoutFrequency21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        txtQualification14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification14KeyTyped(evt);
            }
        });
        panelDiet7.add(txtQualification14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 200, 70));

        txtQualification15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification15KeyTyped(evt);
            }
        });
        panelDiet7.add(txtQualification15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        panelDiet6.add(panelDiet7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 770, 150));

        panelDiet8.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nutritional Facts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPurpose9.setText("Product Name");
        panelDiet8.add(lblPurpose9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblWorkoutFrequency26.setText("Type");
        panelDiet8.add(lblWorkoutFrequency26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txtQualification16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification16KeyTyped(evt);
            }
        });
        panelDiet8.add(txtQualification16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 200, 30));

        lblWorkoutFrequency27.setText("Added By");
        panelDiet8.add(lblWorkoutFrequency27, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        txtQualification17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification17KeyTyped(evt);
            }
        });
        panelDiet8.add(txtQualification17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 200, 70));

        txtQualification18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification18KeyTyped(evt);
            }
        });
        panelDiet8.add(txtQualification18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        panelDiet9.setBackground(new java.awt.Color(255, 255, 255, 180));
        panelDiet9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nutritional Facts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N
        panelDiet9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPurpose10.setText("Product Name");
        panelDiet9.add(lblPurpose10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblWorkoutFrequency28.setText("Type");
        panelDiet9.add(lblWorkoutFrequency28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txtQualification19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification19KeyTyped(evt);
            }
        });
        panelDiet9.add(txtQualification19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 200, 30));

        lblWorkoutFrequency29.setText("Added By");
        panelDiet9.add(lblWorkoutFrequency29, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        txtQualification20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification20KeyTyped(evt);
            }
        });
        panelDiet9.add(txtQualification20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 200, 70));

        txtQualification21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualification21KeyTyped(evt);
            }
        });
        panelDiet9.add(txtQualification21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        panelDiet8.add(panelDiet9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 770, 150));

        panelDiet6.add(panelDiet8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 770, 150));

        txtFat1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFat1KeyTyped(evt);
            }
        });
        panelDiet6.add(txtFat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, 30));

        txtChol1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtChol1KeyTyped(evt);
            }
        });
        panelDiet6.add(txtChol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, 30));

        txtProtein1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProtein1KeyTyped(evt);
            }
        });
        panelDiet6.add(txtProtein1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 200, 30));

        txtSodium1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSodium1KeyTyped(evt);
            }
        });
        panelDiet6.add(txtSodium1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 200, 30));

        lblWorkoutFrequency18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mealservice/icons8-calories-29.png"))); // NOI18N
        lblWorkoutFrequency18.setText("       Calorie");
        panelDiet6.add(lblWorkoutFrequency18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lblWorkoutFrequency30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mealservice/icons8-fast-food-drive-thru-29.png"))); // NOI18N
        lblWorkoutFrequency30.setText("    Total Fat");
        panelDiet6.add(lblWorkoutFrequency30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, -1));

        lblWorkoutFrequency31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mealservice/icons8-low-cholesterol-food-29.png"))); // NOI18N
        lblWorkoutFrequency31.setText("Cholesterol");
        panelDiet6.add(lblWorkoutFrequency31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, -1));

        lblWorkoutFrequency32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mealservice/icons8-low-salt-29.png"))); // NOI18N
        lblWorkoutFrequency32.setText("           Sodium");
        panelDiet6.add(lblWorkoutFrequency32, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        lblWorkoutFrequency19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mealservice/icons8-carbohydrates-29.png"))); // NOI18N
        lblWorkoutFrequency19.setText("Carbohydrates");
        panelDiet6.add(lblWorkoutFrequency19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        lblWorkoutFrequency33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mealservice/icons8-protein-29.png"))); // NOI18N
        lblWorkoutFrequency33.setText("            Protein");
        panelDiet6.add(lblWorkoutFrequency33, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        lblPurpose7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mealservice/icons8-industrial-scales-connected-29.png"))); // NOI18N
        lblPurpose7.setText("Reference Quantity");
        panelDiet6.add(lblPurpose7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        pnlView.add(panelDiet6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 750, 190));

        btnSend.setBackground(new java.awt.Color(255, 51, 51));
        btnSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSend.setText("Request Approval");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        pnlView.add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 130, 35));

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlView.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 102, 35));

        tabbedPane.addTab("Modifications", pnlView);

        panelMain.add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -9, 840, 620));

        getContentPane().add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 830, 580));

        setSize(new java.awt.Dimension(1019, 641));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void resetForm(){
    
        txtName.setText(null);
        txtRefQty.setText(null);
        txtCalorie.setText(null);
        txtFat.setText(null);
        txtChol.setText(null);
        txtSodium.setText(null);
        txtCarbs.setText(null);
        txtProtein.setText(null);

    }
    
    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void panelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseClicked
        // TODO add your handling code here:
        LoginFrame frame = new LoginFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_panelLogoutMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        ManageUsersSA frame = new ManageUsersSA();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void panelProductsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelProductsKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_panelProductsKeyPressed

    private void panelProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProductsMouseClicked
        // TODO add your handling code here:
        System.out.print("open register");
        GSManageProduct addprd = new GSManageProduct();
        addprd.setVisible(true);
        dispose();
    }//GEN-LAST:event_panelProductsMouseClicked

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        // TODO add your handling code here:
        char typedName = evt.getKeyChar();
        if(!Character.isAlphabetic(typedName) && !Character.isWhitespace(typedName)){
            evt.consume();
        }
        //Restrict the length to 256
        if(txtName.getText().length() > 255){
            evt.consume();
        }
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtTypeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTypeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeKeyTyped

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String pname = txtName.getText();
        String type = txtType.getText();
        float ref_qty = Float.parseFloat(txtRefQty.getText());
        float calorie = Float.parseFloat(txtCalorie.getText());
        float fat = Float.parseFloat(txtFat.getText());
        float chol = Float.parseFloat(txtChol.getText());
        float sodium = Float.parseFloat(txtSodium.getText());
        float carbs = Float.parseFloat(txtCarbs.getText());
        float protein = Float.parseFloat(txtProtein.getText());

        ProductDirectory product = new ProductDirectory();

        if(product.alreadyExist(pname)){
            JOptionPane.showMessageDialog(this,"The given Meal already exists in the Meal catalog",
                "Meal already exists",JOptionPane.WARNING_MESSAGE);
        }
        else{
            product.addProduct(pname, type, ref_qty, calorie, fat, chol, sodium,
                carbs, protein,this.name);
            JOptionPane.showMessageDialog(this, "Meal is added to the catalog",
                "Meal added",JOptionPane.INFORMATION_MESSAGE);
            resetForm();
            populateTable("");
        }
        
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblProduct1.getSelectedRow();
        model = (DefaultTableModel) tblProduct1.getModel();

        if(tblProduct1.getSelectedRowCount()==1){
            String pname = txtName.getText();
            String type = txtType.getText();
            float refqty = Float.parseFloat(txtRefQty.getText());
            float calorie = Float.parseFloat(txtCalorie.getText());
            float fat = Float.parseFloat(txtFat.getText());
            float chol = Float.parseFloat(txtChol.getText());
            float sodium = Float.parseFloat(txtSodium.getText());
            float carbs = Float.parseFloat(txtCarbs.getText());
            float protein = Float.parseFloat(txtProtein.getText());

            ProductDirectory product = new ProductDirectory();
            product.updateProduct(type,refqty,calorie,fat,chol,sodium,carbs,protein,pname);
            resetForm();
            populateTable("");
            JOptionPane.showMessageDialog(this, "Meal is updated in the catalog!",
                "Meal updated",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblProduct1.getSelectedRow();
        model = (DefaultTableModel) tblProduct1.getModel();

        String product_name = model.getValueAt(selectedRow,0).toString();

        ProductApproval product = new ProductApproval();

        product.sendProduct(product_name);

        JOptionPane.showMessageDialog(this, "Meal is requested for approval!",
            "Meal requested",JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnSendActionPerformed

    private void txtRefQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRefQtyKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRefQtyKeyTyped

    private void txtCarbsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarbsKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarbsKeyTyped

    private void txtCalorieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalorieKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalorieKeyTyped

    private void txtQualification4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification4KeyTyped

    private void txtQualification5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification5KeyTyped

    private void txtQualification6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification6KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification6KeyTyped

    private void txtQualification7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification7KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification7KeyTyped

    private void txtQualification8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification8KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification8KeyTyped

    private void txtQualification9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification9KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification9KeyTyped

    private void txtQualification10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification10KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification10KeyTyped

    private void txtQualification11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification11KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification11KeyTyped

    private void txtQualification12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification12KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification12KeyTyped

    private void txtFatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFatKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFatKeyTyped

    private void txtCholKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCholKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCholKeyTyped

    private void txtProteinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProteinKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProteinKeyTyped

    private void txtSodiumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSodiumKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSodiumKeyTyped

    private void txtCalorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalorieActionPerformed

    private void txtName2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtName2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName2KeyTyped

    private void txtType1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtType1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtType1KeyTyped

    private void txtRefQty1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRefQty1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRefQty1KeyTyped

    private void txtCarbs1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarbs1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarbs1KeyTyped

    private void txtCalorie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalorie1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalorie1ActionPerformed

    private void txtCalorie1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalorie1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalorie1KeyTyped

    private void txtQualification13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification13KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification13KeyTyped

    private void txtQualification14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification14KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification14KeyTyped

    private void txtQualification15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification15KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification15KeyTyped

    private void txtQualification16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification16KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification16KeyTyped

    private void txtQualification17KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification17KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification17KeyTyped

    private void txtQualification18KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification18KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification18KeyTyped

    private void txtQualification19KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification19KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification19KeyTyped

    private void txtQualification20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification20KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification20KeyTyped

    private void txtQualification21KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualification21KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualification21KeyTyped

    private void txtFat1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFat1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFat1KeyTyped

    private void txtChol1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChol1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChol1KeyTyped

    private void txtProtein1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProtein1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProtein1KeyTyped

    private void txtSodium1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSodium1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSodium1KeyTyped

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblProduct1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProduct1MouseClicked
        // TODO add your handling code here:
        int selectedRow = tblProduct1.getSelectedRow();
        model = (DefaultTableModel) tblProduct1.getModel();

        String product_name = model.getValueAt(selectedRow,0).toString();
        ProductDirectory product = new ProductDirectory();

        ResultSet res = product.exactProductWithStatusLookup(product_name);
        String status = "";
        try {
            while(res.next()){
                status=res.getString("status");
            txtName2.setText(res.getString(1));
            txtType1.setText(res.getString(2));
            txtRefQty1.setText(res.getString(3));
            txtCalorie1.setText(res.getString(4));
            txtFat1.setText(res.getString(5));
            txtChol1.setText(res.getString(6));
            txtSodium1.setText(res.getString(7));
            txtCarbs1.setText(res.getString(8));
            txtProtein1.setText(res.getString(9));
        }}
            catch (SQLException ex) {
            Logger.getLogger(MSManageProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(status.equals("Approved")){
            btnSend.setEnabled(false);
        }
        else{
            btnSend.setEnabled(true);
        }
    }//GEN-LAST:event_tblProduct1MouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String search = txtSearch.getText();
        populateTable(search);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        MSHomePage mf = new MSHomePage(this.name, 0);
        mf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MSManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MSManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MSManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MSManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MSManageProduct().setVisible(true);
            }
        });
    }
    
    private void populateTable(String search) {
        ProductDirectory product = new ProductDirectory();
        ResultSet res = product.getProductData(search,"Meal Plan Product");
        tblProduct1.setModel(DbUtils.resultSetToTableModel(res));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAllergies2;
    private javax.swing.JLabel lblAllergies4;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblHeight2;
    private javax.swing.JLabel lblPurpose10;
    private javax.swing.JLabel lblPurpose3;
    private javax.swing.JLabel lblPurpose4;
    private javax.swing.JLabel lblPurpose5;
    private javax.swing.JLabel lblPurpose6;
    private javax.swing.JLabel lblPurpose7;
    private javax.swing.JLabel lblPurpose8;
    private javax.swing.JLabel lblPurpose9;
    private javax.swing.JLabel lblWorkoutFrequency10;
    private javax.swing.JLabel lblWorkoutFrequency11;
    private javax.swing.JLabel lblWorkoutFrequency12;
    private javax.swing.JLabel lblWorkoutFrequency13;
    private javax.swing.JLabel lblWorkoutFrequency14;
    private javax.swing.JLabel lblWorkoutFrequency15;
    private javax.swing.JLabel lblWorkoutFrequency16;
    private javax.swing.JLabel lblWorkoutFrequency17;
    private javax.swing.JLabel lblWorkoutFrequency18;
    private javax.swing.JLabel lblWorkoutFrequency19;
    private javax.swing.JLabel lblWorkoutFrequency20;
    private javax.swing.JLabel lblWorkoutFrequency21;
    private javax.swing.JLabel lblWorkoutFrequency22;
    private javax.swing.JLabel lblWorkoutFrequency23;
    private javax.swing.JLabel lblWorkoutFrequency24;
    private javax.swing.JLabel lblWorkoutFrequency25;
    private javax.swing.JLabel lblWorkoutFrequency26;
    private javax.swing.JLabel lblWorkoutFrequency27;
    private javax.swing.JLabel lblWorkoutFrequency28;
    private javax.swing.JLabel lblWorkoutFrequency29;
    private javax.swing.JLabel lblWorkoutFrequency30;
    private javax.swing.JLabel lblWorkoutFrequency31;
    private javax.swing.JLabel lblWorkoutFrequency32;
    private javax.swing.JLabel lblWorkoutFrequency33;
    private javax.swing.JPanel panelControl;
    private javax.swing.JPanel panelDiet2;
    private javax.swing.JPanel panelDiet3;
    private javax.swing.JPanel panelDiet4;
    private javax.swing.JPanel panelDiet5;
    private javax.swing.JPanel panelDiet6;
    private javax.swing.JPanel panelDiet7;
    private javax.swing.JPanel panelDiet8;
    private javax.swing.JPanel panelDiet9;
    private javax.swing.JLabel panelLogout;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelMedical;
    private javax.swing.JPanel panelMedical2;
    private javax.swing.JLabel panelProducts;
    private javax.swing.JPanel panelRed;
    private javax.swing.JPanel panelTop;
    private javax.swing.JPanel panellGreen;
    private javax.swing.JPanel pnlRegistration;
    private javax.swing.JPanel pnlView;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tblProduct1;
    private javax.swing.JTextField txtCalorie;
    private javax.swing.JTextField txtCalorie1;
    private javax.swing.JTextField txtCarbs;
    private javax.swing.JTextField txtCarbs1;
    private javax.swing.JTextField txtChol;
    private javax.swing.JTextField txtChol1;
    private javax.swing.JTextField txtFat;
    private javax.swing.JTextField txtFat1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtProtein;
    private javax.swing.JTextField txtProtein1;
    private javax.swing.JTextField txtQualification10;
    private javax.swing.JTextField txtQualification11;
    private javax.swing.JTextField txtQualification12;
    private javax.swing.JTextField txtQualification13;
    private javax.swing.JTextField txtQualification14;
    private javax.swing.JTextField txtQualification15;
    private javax.swing.JTextField txtQualification16;
    private javax.swing.JTextField txtQualification17;
    private javax.swing.JTextField txtQualification18;
    private javax.swing.JTextField txtQualification19;
    private javax.swing.JTextField txtQualification20;
    private javax.swing.JTextField txtQualification21;
    private javax.swing.JTextField txtQualification4;
    private javax.swing.JTextField txtQualification5;
    private javax.swing.JTextField txtQualification6;
    private javax.swing.JTextField txtQualification7;
    private javax.swing.JTextField txtQualification8;
    private javax.swing.JTextField txtQualification9;
    private javax.swing.JTextField txtRefQty;
    private javax.swing.JTextField txtRefQty1;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSodium;
    private javax.swing.JTextField txtSodium1;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtType1;
    // End of variables declaration//GEN-END:variables

    
}
